### ISSUE TITLE
atomikos recovery no operations allowed after connection closed

### ISSUE THREAD

**Issue by hx78** [atomikos/transactions-essentials#116]
we use atomikos jta 4.0.6 and dbcp2 datasource pool 2.7.0。

After the service has been running for a period of time, an exception will be throwed

 [com.atomikos.recovery.xa.XaResourceRecoveryManager : 40] - Error while retrieving xids from resource - will retry later...
com.mysql.jdbc.jdbc2.optional.MysqlXAException: No operations allowed after connection closed.
        at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:608)
        at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.recover(MysqlXAConnection.java:335)
        at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.recover(MysqlXAConnection.java:255)
        at com.atomikos.datasource.xa.RecoveryScan.recoverXids(RecoveryScan.java:32)
        at com.atomikos.recovery.xa.XaResourceRecoveryManager.retrievePreparedXidsFromXaResource(XaResourceRecoveryManager.java:158)
        at com.atomikos.recovery.xa.XaResourceRecoveryManager.recover(XaResourceRecoveryManager.java:67)
        at com.atomikos.datasource.xa.XATransactionalResource.recover(XATransactionalResource.java:451)
        at com.atomikos.icatch.imp.TransactionServiceImp.performRecovery(TransactionServiceImp.java:490)
        at com.atomikos.icatch.imp.TransactionServiceImp.access$000(TransactionServiceImp.java:56)
        at com.atomikos.icatch.imp.TransactionServiceImp$1.alarm(TransactionServiceImp.java:471)
        at com.atomikos.timing.PooledAlarmTimer.notifyListeners(PooledAlarmTimer.java:95)
        at com.atomikos.timing.PooledAlarmTimer.run(PooledAlarmTimer.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Q:
1、What is the cause of this exception？
2、how to disable recovery funtion?

**Comment by GuyPardon** [comment]
Thanks for closing. Looks like a shutdown issue?

**Comment by mandarlaad** [comment]
[hx78](https://github.com/hx78) - Could you please share how you were able to resolve this issue? The same error/warnings are being logged several K times in the log of my spring boot app which runs on an azure app service. The app makes connections to a postgres DB and uses atomikos (via spring boot jta library) for txn mgmt.

**Comment by mandarlaad** [comment]
Sharing connection properties, just in case if those help understand the issue better -

# Connection Pool
minPoolSize=1
maxPoolSize=3
borrowConnectionTimeout=PT10S
idleConnectionTimeout=PT30S
maxConnectionLifetime=PT0S
poolMaintenanceInterval=PT10S
testQuery=SELECT 1
collectHqlMetrics=true

# JPA
enableJta=true
showSql=false
dialect=org.hibernate.dialect.PostgreSQL9Dialect

Also do suggest whether manipulating any of the relevant atomikos configuration properties would help address this issue. Thank you
