### ISSUE TITLE
Does Atomikos import asm (https://asm.ow2.io/) transitively?

### ISSUE THREAD

**Issue by gimantha** [atomikos/transactions-essentials#117]
**Describe the bug**

**To Reproduce**

 1. What you were doing (or trying to do)
I was trying to add atomikos as a dependency to my gradle project by adding 'com.atomikos:transactions-jta:3.6.4'. Some of the modules in my project uses ASM to for code generation. 
 1. What happened
When I tried to build the project, I got the following exception. 
```
Exception in thread "main" java.lang.NoSuchMethodError: org.objectweb.asm.ClassWriter.<init>(I)V
        at org.wso2.ballerinalang.compiler.bir.codegen.BallerinaClassWriter.<init>(BallerinaClassWriter.java:33)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateShutdownSignalListener(JvmPackageGen.java:381)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:477)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:144)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:118)
        at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:310)
        at org.wso2.ballerinalang.compiler.CompilerDriver.getLangModuleFromSource(CompilerDriver.java:379)
        at org.wso2.ballerinalang.compiler.CompilerDriver.loadLangModules(CompilerDriver.java:180)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:148)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
        at org.ballerinalang.stdlib.utils.GenerateBalo.genBalo(GenerateBalo.java:130)
        at org.ballerinalang.stdlib.utils.GenerateBalo.main(GenerateBalo.java:89)
```

 1. What you expected to happen instead
I added it as just a dependency, i expected the project to be built successfully. 
 1. What TransactionsEssentials version you are using
It is transaction-jta:3.6.4

**Additional context**

_I understand that this project is not intended for support - because bug reports may or may not be considered for inclusion some day (in a future release). If this is issue is important to me then I can go to https://www.atomikos.com/Main/SupportOverview and arrange a paid support subscription._

**Comment by GuyPardon** [comment]
Looks like a class loading issue.

Did you try with TransactionsEssentials 5.0?

**Comment by gimantha** [comment]
> Looks like a class loading issue.
> 
> Did you try with TransactionsEssentials 5.0?

Thank you for the reply @GuyPardon 
Yes.. I tried with all the versions. It gives me the same error.. I checked the dependencies and could find that there is an ASM transitive dependancy from hibernate. So i excluded it. Then I was able to resolve the issue. Thanks. I will close the issue, as I was able to solve the issue.
