### ISSUE TITLE
the XA resource has become unavailable

### ISSUE THREAD

**Issue by GodBlessWorld** [atomikos/transactions-essentials#131]
I can still seeing the same issue with atomikos 4.0.6 version with spring boot 2.2.6.RELEASE. Will there be any fix for this?
hi ：
  i use atomikos 4.0.6 version with spring boot 2.2.6.RELEASE. I see some errors like this：
[33m2020-10-25 03:00:05 WARN  com.atomikos.jdbc.JdbcConnectionProxyHelper.logWarning() @40 - Error enlisting in transaction - connection might be broken? Please check the logs for more information...
[m com.atomikos.datasource.ResourceException: XA resource 'orgmgr': resume for XID '3139322E3136382E3137312E3133352E746D313630333536363030353437313030303137:3139322E3136382E3137312E3133352E746D3134' raised -7: the XA resource has become unavailable
	at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:303) ~[transactions-jta-4.0.6.jar!/:?]
	at com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40) ~[transactions-jta-4.0.6.jar!/:?]
	at com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46) ~[transactions-jta-4.0.6.jar!/:?]
	at com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:70) ~[transactions-jta-4.0.6.jar!/:?]
	at com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:160) ~[transactions-jta-4.0.6.jar!/:?]
	at com.atomikos.jdbc.AtomikosConnectionProxy.enlist(AtomikosConnectionProxy.java:207) ~[transactions-jdbc-4.0.6.jar!/:?]
	at com.atomikos.jdbc.AtomikosConnectionProxy.invoke(AtomikosConnectionProxy.java:122) ~[transactions-jdbc-4.0.6.jar!/:?]
	at com.sun.proxy.$Proxy210.prepareStatement(Unknown Source) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor332.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55) ~[mybatis-3.5.3.jar!/:3.5.3]
	at com.sun.proxy.$Proxy213.prepareStatement(Unknown Source) ~[?:?]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86) ~[mybatis-3.5.3.jar!/:3.5.3]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88) ~[mybatis-3.5.3.jar!/:3.5.3]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59) ~[mybatis-3.5.3.jar!/:3.5.3]
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:87) ~[mybatis-3.5.3.jar!/:3.5.3]

**Comment by GuyPardon** [comment]
Looks like a broken connection that will be replaced in the pool.
