### ISSUE TITLE
How to set JNDI datasource to AtomikosDatasourceBean?

### ISSUE THREAD

**Issue by yutou1064** [atomikos/transactions-essentials#136]
i am using springboot+jndi+atomikos+websphere,i get the xaDatasource from websphere,but how can i set it into AtomikosDatasourceBean?

i also tried like this:

Hashtable<String, String> props = new Hashtable<String, String>();
props.put(Context.INITIAL_CONTEXT_FACTORY, AtomikosContextFactory.class.getName());
Context ctx = new InitialContext(props);

but get the error:
 javax.naming.OperationNotSupportedException: null
	at com.atomikos.jndi.AtomikosContext.getEnvironment(AtomikosContext.java:190)
	at org.apache.aries.jndi.DelegateContext.<init>(DelegateContext.java:63)
	at org.apache.aries.jndi.ContextHelper.getInitialContext(ContextHelper.java:144)
	at org.apache.aries.jndi.OSGiInitialContextFactoryBuilder.getInitialContext(OSGiInitialContextFactoryBuilder.java:51)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:695)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:324)
...

**Comment by GuyPardon** [comment]
We have no known issue like this so I can't give a ready made solution.

Please consider a free trial so we can assist you:

https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial
