### ISSUE TITLE
Log corrupted - restart JVM in 5.0.8

### ISSUE THREAD

**Issue by kschroiff** [atomikos/transactions-essentials#139]
Affected version: Transactions Essentials 5.0.8

This seems to be related to an issue that has been previously reported in 4.0.x ( https://fogbugz.atomikos.com/defaultc4d2.html?community.6.3467.7 )

The operation is performing some user updates/creation in the database from a spawned thread.

The (previously functional) code has been ported from a JBoss JEE environment to Spring Boot 2.4.2. 

I'm still investigating the issues - while the code is meant for a bulk operation, the issue seems to occur with single-user updates already so it's not related to data volume.

The exception occurs upon exiting a transactional Spring bean but still within the spawned thread.

```
@Service
@Transactional(propagation = Propagation.REQUIRED, readOnly = false, rollbackFor = Exception.class)
```

The target method in the bean is executed numerous times in other scopes - thus this seems to point to an issue with the execution when being part of a spawned thread ( similar to what was reported for 4.0.x already ).

We are the following exception in our logs upon a commit.

```
org.springframework.transaction.TransactionSystemException: JTA failure on commit; nested exception is com.atomikos.icatch.jta.ExtendedSystemException: Error in rollback: could not flush state image java.nio.channels.ClosedByInterruptException com.atomikos.recovery.LogWriteException
    at deployment.access-service.war//org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1051)
    at deployment.access-service.war//com.xxxx.services.login.LoginMgrServiceBean$$EnhancerBySpringCGLIB$$c67a664f.updateUser(<generated>)
    at deployment.access-service.war//com.xxxx.action.bulk.BulkOperationUsers$2.postOperation(BulkOperationUsers.java:79)
    at deployment.access-service.war//com.xxxx.action.bulk.BulkOperationEngine.next(BulkOperationEngine.java:242)
    at deployment.access-service.war//org.xxxx.threadmgr.SandboxedRunnable.run(SandboxedRunnable.java:107)
    at deployment.access-service.war//org.xxxx.threadmgr.SandboxedThread.run(SandboxedThread.java:134)
Caused by: com.atomikos.icatch.jta.ExtendedSystemException: Error in rollback: could not flush state image java.nio.channels.ClosedByInterruptException com.atomikos.recovery.LogWriteException
    at deployment.access-service.war//com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:175)
    at deployment.access-service.war//com.atomikos.icatch.jta.TransactionManagerImp.commit(TransactionManagerImp.java:428)
    at deployment.access-service.war//com.atomikos.icatch.jta.UserTransactionImp.commit(UserTransactionImp.java:86)
    ... 5 more
Caused by: com.atomikos.icatch.SysException: Error in rollback: could not flush state image java.nio.channels.ClosedByInterruptException com.atomikos.recovery.LogWriteException
    at deployment.access-service.war//com.atomikos.icatch.imp.CoordinatorStateHandler.rollbackFromWithinCallback(CoordinatorStateHandler.java:518)
    at deployment.access-service.war//com.atomikos.icatch.imp.ActiveStateHandler$7.doRollback(ActiveStateHandler.java:290)
    at deployment.access-service.war//com.atomikos.icatch.imp.CoordinatorStateHandler.rollbackWithAfterCompletionNotification(CoordinatorStateHandler.java:569)
    at deployment.access-service.war//com.atomikos.icatch.imp.ActiveStateHandler.rollback(ActiveStateHandler.java:285)
    at deployment.access-service.war//com.atomikos.icatch.imp.CoordinatorImp.rollback(CoordinatorImp.java:579)
    at deployment.access-service.war//com.atomikos.icatch.imp.TransactionStateHandler.rollback(TransactionStateHandler.java:171)
    at deployment.access-service.war//com.atomikos.icatch.imp.TransactionStateHandler.commit(TransactionStateHandler.java:225)
    at deployment.access-service.war//com.atomikos.icatch.imp.CompositeTransactionImp.doCommit(CompositeTransactionImp.java:234)
    at deployment.access-service.war//com.atomikos.icatch.imp.CompositeTransactionImp.commit(CompositeTransactionImp.java:274)
    at deployment.access-service.war//com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:168)
    ... 7 more
Caused by: java.lang.IllegalStateException: could not flush state image java.nio.channels.ClosedByInterruptException com.atomikos.recovery.LogWriteException
    at deployment.access-service.war//com.atomikos.persistence.imp.StateRecoveryManagerImp.preEnter(StateRecoveryManagerImp.java:54)
    at deployment.access-service.war//com.atomikos.finitestates.FSMImp.notifyListeners(FSMImp.java:164)
    at deployment.access-service.war//com.atomikos.finitestates.FSMImp.setState(FSMImp.java:251)
    at deployment.access-service.war//com.atomikos.icatch.imp.CoordinatorImp.setState(CoordinatorImp.java:284)
    at deployment.access-service.war//com.atomikos.icatch.imp.CoordinatorImp.setStateHandler(CoordinatorImp.java:203)
    at deployment.access-service.war//com.atomikos.icatch.imp.CoordinatorStateHandler.rollbackFromWithinCallback(CoordinatorStateHandler.java:512)
    ... 16 more
Caused by: com.atomikos.recovery.LogWriteException: java.nio.channels.ClosedByInterruptException
    at deployment.access-service.war//com.atomikos.recovery.fs.FileSystemRepository.writeCheckpoint(FileSystemRepository.java:203)
    at deployment.access-service.war//com.atomikos.recovery.fs.CachedRepository.performCheckpoint(CachedRepository.java:84)
    at deployment.access-service.war//com.atomikos.recovery.fs.CachedRepository.put(CachedRepository.java:77)
    at deployment.access-service.war//com.atomikos.recovery.fs.OltpLogImp.write(OltpLogImp.java:46)
    at deployment.access-service.war//com.atomikos.persistence.imp.StateRecoveryManagerImp.preEnter(StateRecoveryManagerImp.java:51)
    ... 21 more
Caused by: java.nio.channels.ClosedByInterruptException
    at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
    at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
    at java.base/sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:465)
    at deployment.access-service.war//com.atomikos.recovery.fs.FileSystemRepository.writeCheckpoint(FileSystemRepository.java:196)
```

**Comment by kschroiff** [comment]
FWIW, the issue was related to an entity that was managed in two different session scopes, it seems.

This produced an org.hibernate.AssertionFailure which in turn corrupted the log.

**Comment by GuyPardon** [comment]
This does not seem like a Hibernate thing: ClosedByInterruptException.

**Comment by kschroiff** [comment]
Once I refreshed the entity using the local hibernate session, the issue was gone ...

**Comment by GuyPardon** [comment]
Thanks for sharing!
