### ISSUE TITLE
MySQL XAER_INVAL: Invalid arguments (or unsupported command)

### ISSUE THREAD

**Issue by kschroiff** [atomikos/transactions-essentials#140]
Spring Boot 2.4.3
Essentials 5.0.8
MySQL driver 8.0.22
MySQL 5.6.48

As advised in the docs (and suggested over at stackoverflow), we have set 
* com.atomikos.icatch.serial_jta_transactions=false (this is also showing up in the logs at boot time)
* mysqlXaDataSource.setPinGlobalTxToPhysicalConnection(true); 

Note:
* we also tried to set the PinGlobalTx property in the AtomikosDataSourceBean and directly in the MySQL connection string as well as setting spring.jta.atomikos.properties.serial-jta-transactions=false

Yet we are still seeing the XAER_INVAL exception below. The problem is ... this is only happening "sometimes". We have had regression test runs where the issue below does NOT show up.

If it pops up the server becomes unresponsive though.

```
com.atomikos.datasource.ResourceException: XA resource 'xadslibrary': resume for XID 'XID: 3137322E31362E3135392E32382E746D313631343636393531313832383039343032:3137322E31362E3135392E32382E746D38383431' raised -5: invalid arguments were given for the XA operation
	at deployment.access-service.war//com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:225)
	at deployment.access-service.war//com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40)
	at deployment.access-service.war//com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46)
	at deployment.access-service.war//com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:58)
	at deployment.access-service.war//com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:163)
	at deployment.access-service.war//com.atomikos.jdbc.internal.AtomikosJdbcConnectionProxy.enlist(AtomikosJdbcConnectionProxy.java:88)
	at deployment.access-service.war//com.atomikos.jdbc.internal.AtomikosJdbcConnectionProxy.updateTransactionContext(AtomikosJdbcConnectionProxy.java:61)
	at deployment.access-service.war//com.atomikos.jdbc.internal.AbstractJdbcConnectionProxy.prepareStatement(AbstractJdbcConnectionProxy.java:64)
	at deployment.access-service.war//com.atomikos.util.DynamicProxySupport.callProxiedMethod(DynamicProxySupport.java:159)
	at deployment.access-service.war//com.atomikos.util.DynamicProxySupport.invoke(DynamicProxySupport.java:116)
	at deployment.access-service.war//com.sun.proxy.$Proxy94.prepareStatement(Unknown Source)
	at deployment.access-service.war//org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:90)
	at deployment.access-service.war//org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	at deployment.access-service.war//org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:81)
	at deployment.access-service.war//org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3441)
	at deployment.access-service.war//org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3359)
	at deployment.access-service.war//org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3773)
	at deployment.access-service.war//org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:201)
	at deployment.access-service.war//org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at deployment.access-service.war//org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at deployment.access-service.war//org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
	at deployment.access-service.war//org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
	at deployment.access-service.war//org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
	at deployment.access-service.war//org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
	at deployment.access-service.war//org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1362)
	at deployment.access-service.war//org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1349)
	at deployment.access-service.war//com.sun.proxy.$Proxy170.flush(Unknown Source)
	at deployment.access-service.war//com.sun.proxy.$Proxy170.flush(Unknown Source)
	at deployment.access-service.war//com.xxxx.services.offer.OfferMgrServiceBean.registerCustomer(OfferMgrServiceBean.java:350)
	at deployment.access-service.war//com.xxxx.services.offer.OfferMgrServiceBean$$FastClassBySpringCGLIB$$c80fd230.invoke(<generated>)
	at deployment.access-service.war//com.xxxx.dao.rights.RightsSynchronizerAspect.refreshRights(RightsSynchronizerAspect.java:18)
	at deployment.access-service.war//com.xxxx.services.offer.OfferMgrServiceBean$$EnhancerBySpringCGLIB$$aaaefcb5.registerCustomer(<generated>)
	at deployment.access-service.war//com.xxxx.rsrc.offer.RegistrationResource.create(RegistrationResource.java:69)
	at deployment.access-service.war//com.xxxx.security.LoginGuard.doAccept(LoginGuard.java:1015)
	at deployment.access-service.war//com.xxxx.security.LoginGuard.accept(LoginGuard.java:993)
	at deployment.access-service.war//com.xxxx.security.LoginGuard.doHandle(LoginGuard.java:1128)
	at deployment.access-service.war//com.xxxx.access.server.application.GenericApplicationImpl.handle(GenericApplicationImpl.java:107)
	at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
Caused by: com.mysql.cj.jdbc.MysqlXAException: XAER_INVAL: Invalid arguments (or unsupported command)
	at deployment.access-service.war//com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:344)
	at deployment.access-service.war//com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:329)
	at deployment.access-service.war//com.mysql.cj.jdbc.MysqlXAConnection.start(MysqlXAConnection.java:290)
	at deployment.access-service.war//com.mysql.cj.jdbc.SuspendableXAConnection.start(SuspendableXAConnection.java:172)
	at deployment.access-service.war//com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:219)
	... 38 more
Caused by: java.sql.SQLException: XAER_INVAL: Invalid arguments (or unsupported command)
	at deployment.access-service.war//com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at deployment.access-service.war//com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at deployment.access-service.war//com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at deployment.access-service.war//com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at deployment.access-service.war//com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at deployment.access-service.war//com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:323)
	... 41 more
```

**Comment by kschroiff** [comment]
FWIW, the XAER_INVAL issue related to an entity that was persisted and thereafter modified prior to the final commit.

Even so - this shouldn't result in Atomikos/Hibernate going gaga during follow-up ops - which is what happened here.

**Comment by GuyPardon** [comment]
Maybe you're trying to continue a transaction that the DBMS has rolled back already after such java.sql.SQLIntegrityConstraintViolationException.
