### ISSUE TITLE
com.atomikos.datasource.ResourceException: XA resource raised -3: the XA resource detected an internal error 

### ISSUE THREAD

**Issue by ayeshabanu2021** [atomikos/transactions-essentials#150]
com.atomikos.datasource.ResourceException: XA resource raised -3: the XA resource detected an internal error 

It is happening randomly. We are not able to reproduce this issue.

We are using atomikos in our spring batch application. Spring batch jobs are getting failed with this error in our production which causes data delay in systems.  After deleting the batch job execution in the DB ,jobs are completing successfully.

We are not able to find out the rootcause for this issue.

 DB: oracle 19c
 Version:  4.0.6

**Comment by ayeshabanu2021** [comment]
Error Trace:
com.atomikos.datasource.ResourceException: XA resource 'DS-649423a1-b25a-4519-9ba2-2b49bfeb0d6b': resume for XID '31302E36322E3137302E32322E746D313632393931353739343632323038383734:31302E36322E3137302E32322E746D313036313932' raised -3: the XA resource detected an internal error at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:303) at com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40) at com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46) at com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:70) at com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:160) at com.atomikos.jdbc.AtomikosConnectionProxy.enlist(AtomikosConnectionProxy.java:207) at com.atomikos.jdbc.AtomikosConnectionProxy.invoke(AtomikosConnectionProxy.java:122) at com.sun.proxy.$Proxy7.prepareStatement(Unknown Source) at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:246) at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:638) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:695) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:722) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:772) at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192) at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForList(NamedParameterJdbcTemplate.java:290) at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForList(NamedParameterJdbcTemplate.java:297) at com.ikea.pix.internal.crc.etl.QueryBuilderAndRunner.getSourceRepresentation(QueryBuilderAndRunner.java:324) at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.j"

**Comment by GuyPardon** [comment]
This seems like a DB internal error, do you have access to any DB logs / errors?
