### ISSUE TITLE
sometimes throw 'com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state' when xa commit

### ISSUE THREAD

**Issue by ReveeWu** [atomikos/transactions-essentials#16]
```
2017-12-12 19:32:16,213 [create_thread_orderId_1] DEBUG com.atomikos.icatch.imp.CompositeTransactionImp - commit() done (by application) of transaction 192.168.1.100.tm151307833616201579
2017-12-12 19:32:16,213 [create_thread_orderId_1] DEBUG com.atomikos.datasource.xa.XAResourceTransaction - XAResource.end ( 31302E3235332E34342E34362E746D313531333037383333363136323031353739:31302E3235332E34342E34362E746D32393731 , XAResource.TMSUCCESS ) on resource xaDataSourceLoandbMaster represented by XAResource instance com.mysql.jdbc.jdbc2.optional.JDBC4SuspendableXAConnection@49b1e7b7
2017-12-12 19:32:16,223 [create_thread_orderId_1] DEBUG com.atomikos.datasource.xa.XAResourceTransaction - XAResource.prepare ( 31302E3235332E34342E34362E746D313531333037383333363136323031353739:31302E3235332E34342E34362E746D32393731 ) returning OK on resource xaDataSourceLoandbMaster represented by XAResource instance com.mysql.jdbc.jdbc2.optional.JDBC4SuspendableXAConnection@49b1e7b7
2017-12-12 19:32:16,223 [create_thread_orderId_1] DEBUG com.atomikos.datasource.xa.XAResourceTransaction - XAResource.end ( 31302E3235332E34342E34362E746D313531333037383333363136323031353739:31302E3235332E34342E34362E746D32393732 , XAResource.TMSUCCESS ) on resource xaDataSourceAuditDB represented by XAResource instance com.mysql.jdbc.jdbc2.optional.JDBC4SuspendableXAConnection@11e9ce73
2017-12-12 19:32:16,236 [Atomikos:4] DEBUG com.atomikos.recovery.xa.XaResourceRecoveryManager        - Resource 192.168.1.100.tm recovering XID: 192.168.1.100.tm151307833616201579192.168.1.100.tm2971
2017-12-12 19:32:16,239 [create_thread_orderId_1] DEBUG com.atomikos.datasource.xa.XAResourceTransaction - XAResource.prepare ( 31302E3235332E34342E34362E746D313531333037383333363136323031353739:31302E3235332E34342E34362E746D32393732 ) returning OK on resource xaDataSourceAuditDB represented by XAResource instance com.mysql.jdbc.jdbc2.optional.JDBC4SuspendableXAConnection@11e9ce73
2017-12-12 19:32:16,239 [Atomikos:4] DEBUG com.atomikos.recovery.xa.XaResourceRecoveryManager        - Resource 192.168.1.100.tm recovering XID: 192.168.1.100.tm151307833616201579192.168.1.100.tm2972
2017-12-12 19:32:16,239 [Atomikos:4] DEBUG com.atomikos.recovery.xa.XaResourceRecoveryManager        - Resource 192.168.1.100.tm recovering XID: 192.168.1.100.tm151307833616201579192.168.1.100.tm2971
2017-12-12 19:32:16,243 [create_thread_orderId_1] DEBUG com.atomikos.datasource.xa.XAResourceTransaction - XAResource.commit ( 31302E3235332E34342E34362E746D313531333037383333363136323031353739:31302E3235332E34342E34362E746D32393731 , false ) on resource xaDataSourceLoandbMaster represented by XAResource instance com.mysql.jdbc.jdbc2.optional.JDBC4SuspendableXAConnection@49b1e7b7
2017-12-12 19:32:16,244 [Atomikos:4] DEBUG com.atomikos.recovery.xa.XaResourceRecoveryManager        - Presumed abort of xid: 192.168.1.100.tm151307833616201579192.168.1.100.tm2972
2017-12-12 19:32:16,250 [create_thread_orderId_1] DEBUG com.atomikos.datasource.xa.XAResourceTransaction - XAResource.commit ( 31302E3235332E34342E34362E746D313531333037383333363136323031353739:31302E3235332E34342E34362E746D32393732 , false ) on resource xaDataSourceAuditDB represented by XAResource instance com.mysql.jdbc.jdbc2.optional.JDBC4SuspendableXAConnection@11e9ce73
2017-12-12 19:32:16,252 [Atomikos:4] DEBUG com.atomikos.recovery.xa.XaResourceRecoveryManager        - Presumed abort of xid: 192.168.1.100.tm151307833616201579192.168.1.100.tm2971
2017-12-12 19:32:16,258 [create_thread_orderId_1] WARN  com.atomikos.datasource.xa.XAResourceTransaction - XA resource 'xaDataSourceAuditDB': commit for XID '31302E3235332E34342E34362E746D313531333037383333363136323031353739:31302E3235332E34342E34362E746D32393732' raised -7: the XA resource has become unavailable
com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state
        at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:581) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:566) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.commit(MysqlXAConnection.java:543) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.jdbc2.optional.SuspendableXAConnection.commit(SuspendableXAConnection.java:125) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.atomikos.datasource.xa.XAResourceTransaction.commit(XAResourceTransaction.java:555) ~[transactions-jta-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CommitMessage.send(CommitMessage.java:52) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CommitMessage.send(CommitMessage.java:23) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.PropagationMessage.submit(PropagationMessage.java:67) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.Propagator$PropagatorThread.run(Propagator.java:63) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.Propagator.submitPropagationMessage(Propagator.java:42) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorStateHandler.commitFromWithinCallback(CoordinatorStateHandler.java:373) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.IndoubtStateHandler$1.doCommit(IndoubtStateHandler.java:112) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorStateHandler.commitWithAfterCompletionNotification(CoordinatorStateHandler.java:581) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.IndoubtStateHandler.commit(IndoubtStateHandler.java:107) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorImp.commit(CoordinatorImp.java:548) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorImp.terminate(CoordinatorImp.java:690) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CompositeTransactionImp.commit(CompositeTransactionImp.java:282) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:172) [transactions-jta-4.0.5.jar:na]
        at com.atomikos.icatch.jta.TransactionManagerImp.commit(TransactionManagerImp.java:414) [transactions-jta-4.0.5.jar:na]
        at com.atomikos.icatch.jta.UserTransactionImp.commit(UserTransactionImp.java:86) [transactions-jta-4.0.5.jar:na]
        at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1021) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:757) [spring-tx-4.1.6.RELEASE.jar:na]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726) [spring-tx-4.1.6.RELEASE.jar:na]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:521) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.6.RELEASE.jar:na]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [spring-aop-4.1.6.RELEASE.jar:na]
```
Thanks!

**Comment by ReveeWu** [comment]
xaDataSourceAuditDB`s datasource config is:   
```
<property name="uniqueResourceName" value="xaDataSourceAuditDB" />
		<property name="xaDataSourceClassName" value="com.mysql.jdbc.jdbc2.optional.MysqlXADataSource" />
		<property name="xaProperties">
			<props>
				<prop key="url">${db_url}</prop>
				<prop key="user">${db_username}</prop>
				<prop key="password">${db_password}</prop>
			</props>
		</property>
		<property name="minPoolSize" value="10" />
		<property name="maxPoolSize" value="100" />
		<property name="borrowConnectionTimeout" value="30" />
		<property name="testQuery" value="select 1" />
		<property name="maintenanceInterval" value="60" />
```

**Comment by GuyPardon** [comment]
Thanks - can you provide a bit more context?

**Comment by GuyPardon** [comment]
Thanks to @pascalleclercq : can you check if this is a solution? http://fogbugz.atomikos.com/defaulte7bc.html?community.6.1060.2

**Comment by ReveeWu** [comment]
thanks for your reply very much!   
i'm sorry the log file is cleared last time, but there has another error  
first warn like this  
```
 WARN  com.atomikos.icatch.imp.CoordinatorStateHandler - Error in committing: Existing entry: ABORTING incompatible with new entry: COMMITTING - recovery will clean up in the background
java.lang.IllegalStateException: Existing entry: ABORTING incompatible with new entry: COMMITTING
        at com.atomikos.recovery.imp.OltpLogImp.assertEntryIsAllowedInCurrentState(OltpLogImp.java:43) ~[transactions-4.0.5.jar:na]
        at com.atomikos.recovery.imp.OltpLogImp.write(OltpLogImp.java:30) ~[transactions-4.0.5.jar:na]
        at com.atomikos.persistence.imp.StateRecoveryManagerImp.preEnter(StateRecoveryManagerImp.java:51) ~[transactions-4.0.5.jar:na]
        at com.atomikos.finitestates.FSMImp.notifyListeners(FSMImp.java:164) ~[transactions-4.0.5.jar:na]
        at com.atomikos.finitestates.FSMImp.setState(FSMImp.java:251) ~[transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorImp.setState(CoordinatorImp.java:312) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorStateHandler.commitFromWithinCallback(CoordinatorStateHandler.java:346) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.IndoubtStateHandler$1.doCommit(IndoubtStateHandler.java:112) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorStateHandler.commitWithAfterCompletionNotification(CoordinatorStateHandler.java:581) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.IndoubtStateHandler.commit(IndoubtStateHandler.java:107) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorImp.commit(CoordinatorImp.java:548) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CoordinatorImp.terminate(CoordinatorImp.java:690) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.imp.CompositeTransactionImp.commit(CompositeTransactionImp.java:282) [transactions-4.0.5.jar:na]
        at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:172) [transactions-jta-4.0.5.jar:na]
        at com.atomikos.icatch.jta.TransactionManagerImp.commit(TransactionManagerImp.java:414) [transactions-jta-4.0.5.jar:na]
        at com.atomikos.icatch.jta.UserTransactionImp.commit(UserTransactionImp.java:86) [transactions-jta-4.0.5.jar:na]
        at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1021) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
```

then throw another exception on other thread keep 1-2 seconds  and recove by self
```
Caused by: java.sql.SQLException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  PREPARED state
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.jdbc2.optional.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:680) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:58) ~[mybatis-3.1.1.jar:3.1.1]
        at com.sun.proxy.$Proxy71.execute(Unknown Source) ~[na:na]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:41) ~[mybatis-3.1.1.jar:3.1.1]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:66) ~[mybatis-3.1.1.jar:3.1.1]
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:45) ~[mybatis-3.1.1.jar:3.1.1]
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:108) ~[mybatis-3.1.1.jar:3.1.1]
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75) ~[mybatis-3.1.1.jar:3.1.1]
        at sun.reflect.GeneratedMethodAccessor473.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:46) ~[mybatis-3.1.1.jar:3.1.1]
        at com.datatrees.loan.audit.db.plugin.SecuredUpdateInterceptor.intercept(SecuredUpdateInterceptor.java:36) ~[loan-audit-common-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:57) ~[mybatis-3.1.1.jar:3.1.1]
        at com.sun.proxy.$Proxy68.update(Unknown Source) ~[na:na]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:145) ~[mybatis-3.1.1.jar:3.1.1]
        at sun.reflect.GeneratedMethodAccessor476.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:355) ~[mybatis-spring-1.1.1.jar:1.1.1]
        ... 99 common frames omitted

```

**Comment by GuyPardon** [comment]
Looks like a bug we fixed in the commercial distro. We'll port it to the community soon (normally we don't do this often, but this seems to warrant an exception).

**Comment by ReveeWu** [comment]
Thanks

**Comment by JamKage** [comment]
@GuyPardon, was the "Existing entry: ABORTING incompatible with new entry: COMMITTING" fix ever ported to community? We're experiencing the same problem! Thanks

**Comment by GuyPardon** [comment]
Yes, see the release notes of 4.0.6:

https://www.atomikos.com/Blog/TransactionsEssentials4dot0dot6
