### ISSUE TITLE
Release notes for 4.0.5

### ISSUE THREAD

**Issue by vlotarev** [atomikos/transactions-essentials#19]
We start experiencing problems with the latest version (4.0.5). Everything works just fine with the version 4.0.4. Could you please publish release notes for 4.0.5? It would be easier to understand changes from release notes rather than comparing sources.

Thanks in advance,
Vadim

**Comment by GuyPardon** [comment]
Hi,

The 4.0.5 release notes are being prepared (too much work, apologies). Also, we'll have a 4.0.6 coming up so for now please use 4.0.4 and then 4.0.6 when it is available.

Thanks
Guy

PS what issues are you seeing? Maybe we can still add them to 4.0.6

**Comment by vlotarev** [comment]
Hi,

We did not investigate the problem in details but the stacktrace is something like that:

```
Dec 15 12:03:07.334 WARN [pool-3-thread-16]  XAConnectionFactory: failed to create pooled connection - DBMS down or unreachable? (com.atomikos.jdbc.AtomikosXAConnectionFactory:40) 
oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12519, TNS:no appropriate service handler found
 
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:271) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:317) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	... 47 more

Wrapped by: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12519, TNS:no appropriate service handler found
 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:774) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:384) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.xa.client.OracleXADataSource.getPooledConnection(OracleXADataSource.java:507) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.xa.client.OracleXADataSource.getXAConnection(OracleXADataSource.java:146) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at oracle.jdbc.xa.client.OracleXADataSource.getXAConnection(OracleXADataSource.java:103) ~[ojdbc8-12.2.0.1.jar.215528272216521977.jar:12.2.0.1.0]
	at com.atomikos.jdbc.AtomikosXAConnectionFactory.createPooledConnection(AtomikosXAConnectionFactory.java:43) ~[transactions-jdbc-4.0.5.jar.5777599149637199669.jar:?]
	at com.atomikos.datasource.pool.ConnectionPool.createPooledConnection(ConnectionPool.java:98) ~[transactions-jta-4.0.5.jar.3695942073737938996.jar:?]
	at com.atomikos.datasource.pool.ConnectionPool.growPool(ConnectionPool.java:205) ~[transactions-jta-4.0.5.jar.3695942073737938996.jar:?]
	at com.atomikos.datasource.pool.ConnectionPool.retrieveFirstAvailableConnectionAndGrowPoolIfNecessary(ConnectionPool.java:155) ~[transactions-jta-4.0.5.jar.3695942073737938996.jar:?]
	at com.atomikos.datasource.pool.ConnectionPool.findOrWaitForAnAvailableConnection(ConnectionPool.java:141) ~[transactions-jta-4.0.5.jar.3695942073737938996.jar:?]
	at com.atomikos.datasource.pool.ConnectionPool.borrowConnection(ConnectionPool.java:132) ~[transactions-jta-4.0.5.jar.3695942073737938996.jar:?]
	at com.atomikos.jdbc.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:347) ~[transactions-jdbc-4.0.5.jar.5777599149637199669.jar:?]

```
It looks like at some moment there are no more connections available. The same code with the same settings works correctly with 4.0.4. Have you forgotten to close connections somewhere in 4.0.5? :-)

Regards,
Vadim

**Comment by GuyPardon** [comment]
Well we do have a new pool with faster connection validation. Can you try setting concurrentConnectionValidation=false on the datasource? Thanks.

**Comment by vlotarev** [comment]
This property does the magic :-) Now everything works as expected. It would be nice to understand what this property does. Also may be there are other new useful properties.

Thanks,
Vadim

**Comment by vlotarev** [comment]
> To us, it looks like you are hitting Oracle's internal limits in terms of open connections.

It's rather strange why this happens because I set maxPoolSize much lower than maximum number of allowed connections in Oracle ...

**Comment by GuyPardon** [comment]
Well, the new pool is different in that it will start growing faster than the old one. The only explanation I can think of right now is that you are reaching a limit somewhere due to this. This can happen if you never really exhaust(ed) the pool with 4.0.4 but due to the new behaviour (faster growing) you do with 4.0.5

To validate this hypothesis, can you try setting minPoolSize equal to maxPoolSize, but with concurrentConnectionValidation=true (i.e., new pool activated)? If that gives the problem, my hypothesis could be correct.

Thanks

**Comment by vlotarev** [comment]
Well, I assume that you meant to test this hypothesis with concurrentConnectionValidation=false (i.e. with the old pool). Otherwise it's not quite clear what to test as soon as new pool is failed in my environment with any settings of minPool/maxPool. I set minPool = maxPool and concurrentConnectionValidation=false. Everything works correctly. The same settings with concurrentConnectionValidation=true failed. So I guess that in both cases number of opened connections should be the same (and do not hit the limit of the database).

**Comment by GuyPardon** [comment]
Thanks, do you mean concurrentConnectionValidation=true failed during init? What are the TRACE logs saying?

**Comment by vlotarev** [comment]
Re: [atomikos/transactions-essentials] Release notes for 4.0.5 (#19)


It looks like my previous tests were incorrect, sorry. I tested once more and behavior is the same now with both new and old pools (failed) ... It looks like you are right - some limit is really reached somewhere. Will try to investigate, thank you for your fast responses!

**Comment by GuyPardon** [comment]
My pleasure, thanks for the feedback!
