### ISSUE TITLE
Connection pool not getting refreshed after the network outage

### ISSUE THREAD

**Issue by itsanurodh** [atomikos/transactions-essentials#23]
Hi,
I am facing a problem where atomikos transaction fails after the network outage.This happens once after the network outage and then subsequent transactions are successful. The transaction happens on two nodes connected over a WAN. We are using the Atomikos Transaction Manager 3.9.3.

From the application stack trace, we see that the Test Query fails with SQLState(IX000) vendor code(-79716) while obtaining connection from the pool on the remote node. 

After doing a detailed RCA, we found that after the network outage, the first database operation that does the XA transaction fails to execute the test query while getting the connection. This is because its trying to use and exhaust the stale connections to connect to the remote node. The connection is attempted for around ~100 sec before it fails and then destroys the stale connection. This happens unless all the stale connections are exhausted. So, for example, if there are 5 stale connections in the Connection pool, it would take approximately 5 * 100 sec before the control comes back to the Application. Once all the stale connections are exhausted, the next connection attempt succeeds and the XA transaction goes through fine.

This is the method in atomikos which explains why it would take longer to do the first XA transaction after the network outage:
private Reapable retrieveFirstAvailableConnection(HeuristicMessage hmsg)

We have the following queries:

1. The Connection Pool is not getting refreshed after the network outage. Is there a way Atomikos can detect the network outage and refresh the connection pool once the network issues are resolved ?

2. Why does it take around 100 sec or more for the test query to execute and fail in such cases ? Is there a way we can reduce this time and fail fast ?

3. Are such issues fixed in the later releases of Atomikos, e.g. Atomikos version 4.x ?

Below is the full exception stack trace:

`3076044: Oct 04 09:19:20.478 CDT %MADM-LIB_TPL-7-UNK:SQLState(IX000) vendor code(-79716)
3076045: Oct 04 09:19:20.478 CDT %MADM-LIB_TPL-7-UNK:java.sql.SQLException: System or internal error
3076046: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
3076047: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.jdbcx.IfxXASqli.receiveMessage(IfxXASqli.java:140)
3076048: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.jdbc.IfxSqli.executeExecute(IfxSqli.java:2488)
3076049: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.jdbc.IfxSqli.executeExecute(IfxSqli.java:2463)
3076050: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.jdbc.IfxResultSet.b(IfxResultSet.java:394)
3076051: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.jdbc.IfxStatement.a(IfxStatement.java:1333)
3076052: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.jdbc.IfxStatement.executeImpl(IfxStatement.java:1303)
3076053: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.jdbc.IfxStatement.c(IfxStatement.java:1007)
3076054: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.informix.jdbc.IfxStatement.execute(IfxStatement.java:893)
3076055: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.atomikos.jdbc.AtomikosXAPooledConnection.testUnderlyingConnection(AtomikosXAPooledConnection.java:124)
3076056: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.atomikos.datasource.pool.AbstractXPooledConnection.createConnectionProxy(AbstractXPooledConnection.java:71)
3076057: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.atomikos.datasource.pool.ConnectionPool.retrieveFirstAvailableConnection(ConnectionPool.java:209)
3076058: Oct 04 09:19:20.480 CDT %MADM-LIB_TPL-7-UNK:	at com.atomikos.datasource.pool.ConnectionPool.retrieveFirstAvailableConnectionAndGrowPoolIfNecessary(ConnectionPool.java:173)
3076059: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at com.atomikos.datasource.pool.ConnectionPool.findOrWaitForAnAvailableConnection(ConnectionPool.java:160)
3076060: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at com.atomikos.datasource.pool.ConnectionPool.borrowConnection(ConnectionPool.java:151)
3076061: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at com.atomikos.jdbc.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:342)
3076062: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at com.atomikos.jdbc.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:394)
3076063: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
3076064: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:214)
3076065: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at com.sun.proxy.$Proxy36.prepareStatement(Unknown Source)
3076066: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:534)
3076067: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:452)
3076068: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161)
3076069: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1577)
3076070: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.loader.Loader.doQuery(Loader.java:696)
3076071: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
3076072: Oct 04 09:19:20.481 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.loader.Loader.doList(Loader.java:2232)
3076073: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2129)
3076074: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.loader.Loader.list(Loader.java:2124)
3076075: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:401)
3076076: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:363)
3076077: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
3076078: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1149)
3076079: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
3076080: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:88)
3076081: Oct 04 09:19:20.482 CDT %MADM-LIB_TPL-7-UNK:	at com.cisco.persistence.dao.impl.AbstractEntityDAOImpl.getConfigSeedID(AbstractEntityDAOImpl.java:334
)
....
....
3079752: Oct 04 09:26:28.791 CDT %MADM-ADM_CFG-7-UNK:Exception occurred JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException: Prepare: NO vote
`

**Comment by GuyPardon** [comment]
The pool does test connections normally. Would you like to engage in a free trial of our commercial distribution to have us troubleshoot your configuration?

**Comment by itsanurodh** [comment]
Thanks GuyPardon.
The pool does test connections. However, in the case of network disconnect and reconnect, seems like the Test connections to the pool fails, since the broken connections are still available in the pool. So, Atomikos tries to use all the broken connections, until all the connections are exhausted, taking a considerable time, and then finally succeeds to execute the test query.
Is there a way Atomikos can get rid of the broken connections and refresh the pool when such network flap happens ?
I did not find any configuration which would help to achieve this. Could you point to the configurations which would be required to take care of this ?

**Comment by GuyPardon** [comment]
We don't proactively test connections. Any suggestions on what we could do?

**Comment by itsanurodh** [comment]
Not sure if there are many options, but Can Atomikos do periodically test connections based on some defined configuration (e.g. frequency of the test connections)  ? The reason is that the Atomikos transaction is not failing until a long time and finally roll backs in such scenarios. 

Also, the Test query is taking close to 110 sec before it comes back with the connect exceptions. Can this time be reduced ? We are more concerned about the time it takes to know that there are some failures happening because of the network flap. 

I think these concerns would be there with all the applications which supports high availability and dependent on the distributed transactions across nodes in the network.

**Comment by itsanurodh** [comment]
Hi GuyPardon,

Had one more thought. If the first try of the createconnection fails when executing the test query, do we really want to retry all other connections in the pool ? Can we not retry with first connection and if it fails to create the connection, clear all other connections in the pool ?

**Comment by GuyPardon** [comment]
Yes, your last suggestion is also what we were thinking of.

When it comes to reducing the time to get connection exceptions: did you try setting the TCP/IP timeouts of your OS?

**Comment by itsanurodh** [comment]
I did not see any impact of the TCP timeout settings in the OS which is currently set to 5 min. Irrespective, the Query test connection fails after around 110 sec. 
Also, we tried to lower the transaction timeout to reduce the overall operation time, it seems the transaction timeout comes into play only after trying all the half broken connections in the pool.

Regarding the approach  i mentioned in the last thread, are you planning to have this implemented in the latest version of Atomikos essentials ? Please let us know the plan.

**Comment by GuyPardon** [comment]
Regarding the timeout: it is not a known issue AFAIK. We could try to call setNetworkTimeout on the underlying driver connection to set it to the transaction timeout - or slightly higher. Just an idea...

We don't have a habit of systematically releasing open source maintenance releases for the 4.0 because it went out of its public support time window; we did do so recently because we wanted to fix some basic usability issues. So as to where this will be implemented, I can't promise anything. 

We do have over 100 fixes in our commercial edition that are accessible during a free trial if you are interested. Let me know if you're interested in that?

**Comment by itsanurodh** [comment]
Hi GuyPardon,

We have one more suggestion to the problem where closing or refreshing the half broken connections in the pool takes longer time. Can we do this ?
In the ConnectionPool.refresh(), where we are trying to destroy the connection using destroyPooledConnection(conn) in the for loop, can we do this in a separate thread, and call addConnectionsIfMinPoolSizeNotReached() meanwhile. 
This would unblock the operations which is trying to get a new connection to continue. 

Let me know your thoughts on this suggestion.

Regards
Anurodh

**Comment by GuyPardon** [comment]
That might work or not, depending on how you implement it. There is synchronisation to make it thread-safe so the threads may still wait for each other if you do this. Why don't you try in a fork?

**Comment by itsanurodh** [comment]
Sure, I will be trying this locally and will keep you posted.

**Comment by itsanurodh** [comment]
Hi GuyPardon,

I have made the required changes in the forked code. I want to raise a pull request for the same. Could you please grant me the permission so that I can raise a pull request.

**Comment by GuyPardon** [comment]
Hi,

As far as I know, you can create a pull request once you forked our repository, so not sure what I have to do extra. Any hints?

Guy

**Comment by itsanurodh** [comment]
Its giving me the following error when push the changes:

ANURJAIN-M-X1KH:transactions-jta anurjain$ git push origin Atomikos_refreshCP
Username for 'https://github.com': itsanurodh	
Password for 'https://itsanurodh@github.com': 
remote: Permission to atomikos/transactions-essentials.git denied to itsanurodh.
fatal: unable to access 'https://github.com/atomikos/transactions-essentials.git/': The requested URL returned error: 403

**Comment by GuyPardon** [comment]
You can't push to the repo directly, you must first fork it and then create a pull request as explained here: https://help.github.com/articles/creating-a-pull-request/

**Comment by itsanurodh** [comment]
Thanks. Created the pull request.
Please review and provide your inputs.

**Comment by itsanurodh** [comment]
GuyPardon,
Did you get a chance to look at the changes ?
