### ISSUE TITLE
TransactionEssentials 6.0.0 is broken with Spring Boot 3.4.0

### ISSUE THREAD

**Issue by ibmmqmet** [atomikos/transactions-essentials#234]
A JMS program that worked with Spring Boot 3.3.6 is broken with 3.4.0 because of it calling a missing method.

Looks to be the same thing that caused https://github.com/snowdrop/narayana-spring-boot/pull/172

```
APPLICATION FAILED TO START


Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.atomikos.spring.AtomikosAutoConfiguration.lambda$transactionManager$0(AtomikosAutoConfiguration.java:84)

The following method did not exist:

    'void org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizers.customize(org.springframework.transaction.PlatformTransaction
Manager)'

The calling method's class, com.atomikos.spring.AtomikosAutoConfiguration, was loaded from the following location:

    jar:file:/home/metaylor/.gradle/caches/modules-2/files-2.1/com.atomikos/transactions-spring-boot3/6.0.0/d469a4ebaa9a86e0e979dfafd82ecd2bb655e255/tra
nsactions-spring-boot3-6.0.0.jar!/com/atomikos/spring/AtomikosAutoConfiguration.class

The called method's class, org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizers, is available from the following locations:

    jar:file:/home/metaylor/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/3.4.0/2cf78b01be25952c96cb8ee60b4b0562
b3a136f2/spring-boot-autoconfigure-3.4.0.jar!/org/springframework/boot/autoconfigure/transaction/TransactionManagerCustomizers.class

The called method's class hierarchy was loaded from the following locations:

    org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizers: file:/home/metaylor/.gradle/caches/modules-2/files-2.1/org.springf
ramework.boot/spring-boot-autoconfigure/3.4.0/2cf78b01be25952c96cb8ee60b4b0562b3a136f2/spring-boot-autoconfigure-3.4.0.jar

```

**Comment by ibmmqmet** [comment]
Changing `boot.version` in `transactions-essentials/public/spring-boot3/pom.xml`  from 3.0.1 to 3.4.0 and rebuilding from that directory "solves" the problem. But obviously that's not the right thing to do as it forces the version change.

**Comment by thijmenketel** [comment]
I guess an update is not likely as the last PR merge was in march :(

**Comment by jeffjensen** [comment]
@GuyPardon We're wondering if you can fix this and release soon?  This is a blocker to using Atomikos with the latest Boot.

**Comment by cedricmillet** [comment]
up !

**Comment by jeffjensen** [comment]
This is such a blocker with no reply we moved to Narayana, was very easy and works great.

**Comment by GuyPardon** [comment]
Thanks for the update! For blocker issues we offer zoom calls and much more.

**Comment by ollimpet** [comment]
> Thanks for the update! For blocker issues we offer zoom calls and much more.

I think a fix would be preferable. Or are we to assume that transactions-essentials is dead?

**Comment by stefanzugal** [comment]
I acknowledge that @GuyPardon wants to sell services. At the end of the day, everybody has to pay his bills, so that is fine with me. Hence, I had a look whether buying the commercial version would be an option. However, looking at the prices, this is not a viable option. I am afraid that we will also have to leave transactions-essentials behind in case this cannot be fixed. Not meaning to blame anyone, just wanted to share my thoughts.

See: https://www.atomikos.com/Main/BuyOnline

**Comment by GuyPardon** [comment]
it's not about selling services, we fixed this in the community branch but it hasn't been released yet. The official fix in the commercial release hasn't been officially published either, BTW. Thanks for your feedback and patience. Anyone can book a zoom call via our website, as long as there is no abuse we are glad to listen and gather feedback.

Based on this thread here is a custom zoom setup for the community:

https://calendly.com/guypardon/open-source-feedback

**Comment by mpalourdio** [comment]
@GuyPardon any ETA for the commercial release ?

**Comment by m4nh6n** [comment]
A fix (in both community and commercial) would be fantastic! It would be such a pity if projects that use Atomikos would have to fall behind in Spring Boot versions.

Hope you can release one, soon ❤

**Comment by BK-drodi** [comment]
When do you think the community edition will be released that fix this problem?

**Comment by Allenisme** [comment]
Here's a  temporary fix with SpringBoot 3.4.4: 

![Image](https://github.com/user-attachments/assets/fc6dfedb-ae8d-4568-95e2-4f8cdb54e548)

**Comment by BK-drodi** [comment]
> Here's a temporary fix with SpringBoot 3.4.4:
> 
> ![Image](https://github.com/user-attachments/assets/fc6dfedb-ae8d-4568-95e2-4f8cdb54e548)

Works perfectly for me - Thank you very much!

**Comment by m4nh6n** [comment]
Awesome! Upgraded our code already to SB 3.4.4 with this workaround, while we are still waiting for the next release of TransactionEssentials. Thanks a lot @Allenisme !

**Comment by xtermi2** [comment]
Anoter Workaround ist to copy the `com.atomikos.spring.AtomikosAutoConfiguration` to your appication and add to `@AutoConfigureBefore` `com.atomikos.spring.AtomikosAutoConfiguration.class`.

Here is my full exaple:
```java
/**
 * Copyright (C) 2000-2023 Atomikos <info@atomikos.com>
 * <p>
 * LICENSE CONDITIONS
 * <p>
 * See http://www.atomikos.com/Main/WhichLicenseApplies for details.
 */

package com.example.demo;

import com.atomikos.icatch.config.UserTransactionService;
import com.atomikos.icatch.config.UserTransactionServiceImp;
import com.atomikos.icatch.jta.UserTransactionManager;
import com.atomikos.spring.*;
import jakarta.jms.Message;
import jakarta.transaction.TransactionManager;
import jakarta.transaction.UserTransaction;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.autoconfigure.AutoConfigureBefore;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.jms.artemis.ArtemisAutoConfiguration;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;
import org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizers;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.boot.jdbc.XADataSourceWrapper;
import org.springframework.boot.jms.XAConnectionFactoryWrapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.transaction.jta.JtaTransactionManager;

import java.util.Properties;

/**
 * This is a copy of {@link com.atomikos.spring.AtomikosAutoConfiguration} which fixed spring boot 3.4 compatibility
 */
@Configuration(proxyBeanMethods = false)
@EnableConfigurationProperties({SpringJtaAtomikosProperties.class, AtomikosProperties.class})
@ConditionalOnClass({JtaTransactionManager.class, UserTransactionManager.class})
@ConditionalOnMissingBean(org.springframework.transaction.TransactionManager.class)
@AutoConfigureBefore(
        value = {com.atomikos.spring.AtomikosAutoConfiguration.class, XADataSourceAutoConfiguration.class, ArtemisAutoConfiguration.class, HibernateJpaAutoConfiguration.class},
        name = "org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration")
public class AtomikosAutoConfiguration {

    @Bean(initMethod = "init", destroyMethod = "shutdownWait")
    @ConditionalOnMissingBean(UserTransactionService.class)
    UserTransactionServiceImp userTransactionService(SpringJtaAtomikosProperties springJtaAtomikosProperties, AtomikosProperties atomikosProperties) {
        Properties properties = new Properties();
        properties.putAll(springJtaAtomikosProperties.asProperties());
        properties.putAll(atomikosProperties.asProperties());
        return new UserTransactionServiceImp(properties);
    }


    @Bean(initMethod = "init", destroyMethod = "close")
    @ConditionalOnMissingBean(TransactionManager.class)
    UserTransactionManager atomikosTransactionManager(UserTransactionService userTransactionService) throws Exception {
        UserTransactionManager manager = new UserTransactionManager();
        manager.setStartupTransactionService(false);
        manager.setForceShutdown(true);
        return manager;
    }

    @Bean
    @ConditionalOnMissingBean(XADataSourceWrapper.class)
    AtomikosXADataSourceWrapper xaDataSourceWrapper() {
        return new AtomikosXADataSourceWrapper();
    }

    @Bean
    @ConditionalOnMissingBean
    static AtomikosDependsOnBeanFactoryPostProcessor atomikosDependsOnBeanFactoryPostProcessor() {
        return new AtomikosDependsOnBeanFactoryPostProcessor();
    }

    @Bean
    JtaTransactionManager transactionManager(UserTransaction userTransaction, TransactionManager transactionManager,
                                             ObjectProvider<TransactionManagerCustomizers> transactionManagerCustomizers) {
        JtaTransactionManager jtaTransactionManager = new JtaTransactionManager(userTransaction, transactionManager);
        transactionManagerCustomizers.ifAvailable((customizers) -> customizers.customize(jtaTransactionManager));
        return jtaTransactionManager;
    }

    @Configuration(proxyBeanMethods = false)
    @ConditionalOnClass(Message.class)
    static class AtomikosJtaJmsConfiguration {

        @Bean
        @ConditionalOnMissingBean(XAConnectionFactoryWrapper.class)
        AtomikosXAConnectionFactoryWrapper xaConnectionFactoryWrapper() {
            return new AtomikosXAConnectionFactoryWrapper();
        }

    }

}
```

**Comment by hand-of-doom-dg** [comment]
Thanks @xtermi2 . The workaround is brilliant and works on spring 3.4 and 3.5 too.

**Comment by komi-eulisa** [comment]
> Here's a temporary fix with SpringBoot 3.4.4:
> 
> ![Image](https://github.com/user-attachments/assets/fc6dfedb-ae8d-4568-95e2-4f8cdb54e548)

Thanks for your workaround.

I tried it but not working for me.

**My env**:

**spring-boot:** 3.5.5
**atomikos**: com.atomikos:transactions-spring-boot3-starter:6.0.0
**Java**: 21

As error I had this:

com.mysql.cj.jdbc.MysqlXAException: XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
        at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:334) ~[mysql-connector-j-9.2.0.jar:9.2.0]
        at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:179) ~[mysql-connector-j-9.2.0.jar:9.2.0]
        at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:107) ~[mysql-connector-j-9.2.0.jar:9.2.0]
        at com.atomikos.datasource.xa.RecoveryScan.recoverXids(RecoveryScan.java:32) ~[transactions-jta-6.0.0-jakarta.jar!/:?]
        at com.atomikos.recovery.xa.XARecoveryManager.retrievePreparedXidsFromXaResource(XARecoveryManager.java:265) ~[transactions-jta-6.0.0-jakarta.jar!/:?]
        at com.atomikos.recovery.xa.XARecoveryManager.recover(XARecoveryManager.java:93) ~[transactions-jta-6.0.0-jakarta.jar!/:?]
        at com.atomikos.datasource.xa.XATransactionalResource.recover(XATransactionalResource.java:375) [transactions-jta-6.0.0-jakarta.jar!/:?]
        at com.atomikos.icatch.imp.RecoveryDomainService.performRecovery(RecoveryDomainService.java:82) [transactions-6.0.0.jar!/:?]
        at com.atomikos.icatch.imp.TransactionServiceImp.performRecoveryPass(TransactionServiceImp.java:674) [transactions-6.0.0.jar!/:?]
        at com.atomikos.icatch.imp.TransactionServiceImp.shutdown(TransactionServiceImp.java:561) [transactions-6.0.0.jar!/:?]
        at com.atomikos.icatch.config.Configuration.shutdown(Configuration.java:325) [transactions-api-6.0.0.jar!/:?]
        at com.atomikos.icatch.config.UserTransactionServiceImp.shutdown(UserTransactionServiceImp.java:85) [transactions-api-6.0.0.jar!/:?]
        at com.atomikos.icatch.config.UserTransactionServiceImp.shutdownWait(UserTransactionServiceImp.java:158) [transactions-api-6.0.0.jar!/:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:316) [spring-beans-6.2.10.jar!/:6.2.10]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:249) [spring-beans-6.2.10.jar!/:6.2.10]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:798) [spring-beans-6.2.10.jar!/:6.2.10]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:748) [spring-beans-6.2.10.jar!/:6.2.10]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1481) [spring-beans-6.2.10.jar!/:6.2.10]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:707) [spring-beans-6.2.10.jar!/:6.2.10]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1474) [spring-beans-6.2.10.jar!/:6.2.10]
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1219) [spring-context-6.2.10.jar!/:6.2.10]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:640) [spring-context-6.2.10.jar!/:6.2.10]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) [spring-boot-3.5.5.jar!/:3.5.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-3.5.5.jar!/:3.5.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) [spring-boot-3.5.5.jar!/:3.5.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) [spring-boot-3.5.5.jar!/:3.5.5]
        at eu.ecodex.connector.starter.DomibusConnectorStarter.run(DomibusConnectorStarter.java:85) [domibusConnectorStarter-6.0.2-SNAPSHOT.jar!/:?]
        at eu.ecodex.connector.starter.DomibusConnectorStarter.runSpringApplication(DomibusConnectorStarter.java:78) [domibusConnectorStarter-6.0.2-SNAPSHOT.jar!/:?]
        at eu.ecodex.connector.starter.DomibusConnectorStarter.main(DomibusConnectorStarter.java:67) [domibusConnectorStarter-6.0.2-SNAPSHOT.jar!/:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102) [connector.jar:?]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64) [connector.jar:?]
        at org.springframework.boot.loader.launch.PropertiesLauncher.main(PropertiesLauncher.java:580) [connector.jar:?]
Caused by: java.sql.SQLException: XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql-connector-j-9.2.0.jar:9.2.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114) ~[mysql-connector-j-9.2.0.jar:9.2.0]
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1312) ~[mysql-connector-j-9.2.0.jar:9.2.0]
        at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:158) ~[mysql-connector-j-9.2.0.jar:9.2.0]

**Comment by asoldo11** [comment]
is there a roadmap to support Spring Boot 4.0.x? Proposed workaround does not fit to SB4.0 due to complete internal reorganization of package names inside SB :/
