### ISSUE TITLE
com.atomikos.icatch.HeurHazardException: XAResourceTransaction: xxxx: no XAResource to commit?

### ISSUE THREAD

**Issue by xiaofeng010766** [atomikos/transactions-essentials#25]
Caused by: com.mysql.jdbc.jdbc2.optional.MysqlXAException: Undetermined error occurred in the underlying Connection - check your data for consistency
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:584) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:566) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.commit(MysqlXAConnection.java:543) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.SuspendableXAConnection.commit(SuspendableXAConnection.java:125) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.atomikos.datasource.xa.XAResourceTransaction.commit(XAResourceTransaction.java:557) ~[transactions-jta-4.0.6.jar:?]
	... 67 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1232) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1225) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2417) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2401) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:558) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.commit(MysqlXAConnection.java:543) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.SuspendableXAConnection.commit(SuspendableXAConnection.java:125) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.atomikos.datasource.xa.XAResourceTransaction.commit(XAResourceTransaction.java:557) ~[transactions-jta-4.0.6.jar:?]
	... 67 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 132,922 milliseconds ago.  The last packet sent successfully to the server was 18,956 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3327) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3601) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3576) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:765) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:742) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:560) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.start(MysqlXAConnection.java:507) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.SuspendableXAConnection.start(SuspendableXAConnection.java:172) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:297) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:70) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:160) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.jdbc.AtomikosConnectionProxy.enlist(AtomikosConnectionProxy.java:207) ~[transactions-jdbc-4.0.6.jar:?]
	at com.atomikos.jdbc.AtomikosConnectionProxy.invoke(AtomikosConnectionProxy.java:122) ~[transactions-jdbc-4.0.6.jar:?]
	at com.sun.proxy.$Proxy99.createStatement(Unknown Source) ~[?:?]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:402) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:474) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:484) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:510) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.ais.cs.ddi.frame.jdbc.DBOperation.getRowsMapList(DBOperation.java:165) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.frame.jdbc.DBOperation.getRowsMapList(DBOperation.java:132) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.frame.jdbc.DBOperation.getRows(DBOperation.java:186) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.frame.jdbc.DBOperation$$FastClassBySpringCGLIB$$e649bfca.invoke(<generated>) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.ais.cs.ddi.frame.jdbc.DBOperation$$EnhancerBySpringCGLIB$$6add66c5.getRows(<generated>) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.service.persistence.PersistenceServiceImpl.getRows(PersistenceServiceImpl.java:92) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.service.persistence.PersistenceServiceImpl.getRows(PersistenceServiceImpl.java:40) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.service.business.CRUDBusinessServiceImpl.listQueryService(CRUDBusinessServiceImpl.java:1845) ~[csmf-core-4.2.0-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 47 more
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_91]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_91]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[?:1.8.0_91]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_91]
	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:100) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:143) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:173) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2911) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3337) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3327) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3601) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3576) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:765) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:742) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:560) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.start(MysqlXAConnection.java:507) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.mysql.jdbc.jdbc2.optional.SuspendableXAConnection.start(SuspendableXAConnection.java:172) ~[mysql-connector-java-5.1.34.jar:5.1.34]
	at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:297) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:70) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:160) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.jdbc.AtomikosConnectionProxy.enlist(AtomikosConnectionProxy.java:207) ~[transactions-jdbc-4.0.6.jar:?]
	at com.atomikos.jdbc.AtomikosConnectionProxy.invoke(AtomikosConnectionProxy.java:122) ~[transactions-jdbc-4.0.6.jar:?]
	at com.sun.proxy.$Proxy99.createStatement(Unknown Source) ~[?:?]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:402) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:474) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:484) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:510) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.ais.cs.ddi.frame.jdbc.DBOperation.getRowsMapList(DBOperation.java:165) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.frame.jdbc.DBOperation.getRowsMapList(DBOperation.java:132) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.frame.jdbc.DBOperation.getRows(DBOperation.java:186) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.frame.jdbc.DBOperation$$FastClassBySpringCGLIB$$e649bfca.invoke(<generated>) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.ais.cs.ddi.frame.jdbc.DBOperation$$EnhancerBySpringCGLIB$$6add66c5.getRows(<generated>) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.service.persistence.PersistenceServiceImpl.getRows(PersistenceServiceImpl.java:92) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.service.persistence.PersistenceServiceImpl.getRows(PersistenceServiceImpl.java:40) ~[csmf-persistance-4.2.0-SNAPSHOT.jar:?]
	at com.ais.cs.ddi.service.business.CRUDBusinessServiceImpl.listQueryService(CRUDBusinessServiceImpl.java:1845) ~[csmf-core-4.2.0-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 47 more
2018-01-16 20:43:34,392-[HL] ERROR Atomikos:22 com.atomikos.datasource.xa.XAResourceTransaction:22 - XAResourceTransaction: 31302E32312E34302E372E746D313531363130363532313639313030343334:31302E32312E34302E372E746D323838: no XAResource to commit?
2018-01-16 20:43:34,392-[HL] ERROR Atomikos:22 com.atomikos.datasource.xa.XAResourceTransaction:22 - XAResourceTransaction: xxx : no XAResource to commit?
2018-01-16 20:43:34,392-[HL] ERROR Atomikos:22 com.atomikos.icatch.imp.CommitMessage:47 - Unexpected error in commit
com.atomikos.icatch.HeurHazardException: XAResourceTransaction: xxxx: no XAResource to commit?
	at com.atomikos.datasource.xa.XAResourceTransaction.commit(XAResourceTransaction.java:529) ~[transactions-jta-4.0.6.jar:?]
	at com.atomikos.icatch.imp.CommitMessage.send(CommitMessage.java:52) [transactions-4.0.6.jar:?]
	at com.atomikos.icatch.imp.CommitMessage.send(CommitMessage.java:23) [transactions-4.0.6.jar:?]
	at com.atomikos.icatch.imp.PropagationMessage.submit(PropagationMessage.java:67) [transactions-4.0.6.jar:?]
	at com.atomikos.icatch.imp.Propagator$PropagatorThread.run(Propagator.java:63) [transactions-4.0.6.jar:?]
	at com.atomikos.icatch.imp.Propagator.submitPropagationMessage(Propagator.java:42) [transactions-4.0.6.jar:?]
	at com.atomikos.icatch.imp.HeurHazardStateHandler.onTimeout(HeurHazardStateHandler.java:71) [transactions-4.0.6.jar:?]
	at com.atomikos.icatch.imp.CoordinatorImp.alarm(CoordinatorImp.java:650) [transactions-4.0.6.jar:?]
	at com.atomikos.timing.PooledAlarmTimer.notifyListeners(PooledAlarmTimer.java:95) [atomikos-util-4.0.6.jar:?]
	at com.atomikos.timing.PooledAlarmTimer.run(PooledAlarmTimer.java:82) [atomikos-util-4.0.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by GuyPardon** [comment]
Looks like a configuration issue - do you have a budget for support so we can help you?

**Comment by xiaofeng010766** [comment]
The scene of the problem is suddenly stopped for the MySQL database, and then the database is restarted, and the console has been reporting this error.
