### ISSUE TITLE
NPE in AtomikosConnectionProxy.newInstance

### ISSUE THREAD

**Issue by filiplx** [atomikos/transactions-essentials#36]
Hi,
Got a NullPointerException twice now. Both occurances occured in a non-transactional context.
Any ideas on why this happened?

Atomikos release: 4.0.6

**DataSource setup**
Some details have been withheld.
```
AtomikosDataSourceBean dataSource = new AtomikosDataSourceBean();
dataSource.setUniqueResourceName(...);
dataSource.setXaDataSourceClassName(...);
dataSource.setXaProperties(...);
dataSource.setBorrowConnectionTimeout(...);
dataSource.setLoginTimeout(6);
dataSource.setMinPoolSize(0);
dataSource.setMaxPoolSize(...);
dataSource.setTestQuery("/* ping */ select 1");
dataSource.init();
```

BR,
Filip

Caused by: java.lang.NullPointerException
    at com.atomikos.jdbc.AtomikosConnectionProxy.newInstance(AtomikosConnectionProxy.java:246)
    at com.atomikos.jdbc.AtomikosXAPooledConnection.doCreateConnectionProxy(AtomikosXAPooledConnection.java:93)
    at com.atomikos.datasource.pool.AbstractXPooledConnection.createConnectionProxy(AbstractXPooledConnection.java:56)
    at com.atomikos.datasource.pool.ConnectionPoolWithConcurrentValidation.concurrentlyTryToUse(ConnectionPoolWithConcurrentValidation.java:59)
    at com.atomikos.datasource.pool.ConnectionPoolWithConcurrentValidation.retrieveFirstAvailableConnection(ConnectionPoolWithConcurrentValidation.java:41)
    at com.atomikos.datasource.pool.ConnectionPool.retrieveFirstAvailableConnectionAndGrowPoolIfNecessary(ConnectionPool.java:153)
    at com.atomikos.datasource.pool.ConnectionPool.findOrWaitForAnAvailableConnection(ConnectionPool.java:141)
    at com.atomikos.datasource.pool.ConnectionPool.borrowConnection(ConnectionPool.java:132)
    at com.atomikos.jdbc.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:346)
    at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
    at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:225)

**Comment by GuyPardon** [comment]
What release are you using?

**Comment by filiplx** [comment]
Atomikos release: 4.0.6

**Comment by GuyPardon** [comment]
Sorry for the late reply. Never seen this exception before - so it beats me. Let me know how you want to proceed?

**Comment by diogogallo** [comment]
Just got the same exception in the same line. Twice as well.

Same version: 4.0.6

```

exception: java.lang.NullPointerException
	at com.atomikos.jdbc.AtomikosConnectionProxy.newInstance(AtomikosConnectionProxy.java:246)
	at com.atomikos.jdbc.AtomikosXAPooledConnection.doCreateConnectionProxy(AtomikosXAPooledConnection.java:93)
	at com.atomikos.datasource.pool.AbstractXPooledConnection.createConnectionProxy(AbstractXPooledConnection.java:56)
	at com.atomikos.datasource.pool.ConnectionPoolWithConcurrentValidation.concurrentlyTryToUse(ConnectionPoolWithConcurrentValidation.java:59)
	at com.atomikos.datasource.pool.ConnectionPoolWithConcurrentValidation.retrieveFirstAvailableConnection(ConnectionPoolWithConcurrentValidation.java:41)
	at com.atomikos.datasource.pool.ConnectionPool.retrieveFirstAvailableConnectionAndGrowPoolIfNecessary(ConnectionPool.java:153)
	at com.atomikos.datasource.pool.ConnectionPool.findOrWaitForAnAvailableConnection(ConnectionPool.java:141)
	at com.atomikos.datasource.pool.ConnectionPool.borrowConnection(ConnectionPool.java:132)
	at com.atomikos.jdbc.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:346)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:47)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.prepareQueryStatement(AbstractLoadPlanBasedLoader.java:226)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:190)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:121)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:86)
	at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:197)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4278)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:480)
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:450)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:201)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:260)
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:103)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:71)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1286)
	at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:212)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2929)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2910)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2866)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2910)
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3550)
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3522)
	at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:350)
	at com.sun.proxy.$Proxy185.find(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:308)
	at com.sun.proxy.$Proxy185.find(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findById(SimpleJpaRepository.java:234)
	at sun.reflect.GeneratedMethodAccessor395.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy190.findById(Unknown Source)
```

**Comment by GuyPardon** [comment]
Thanks - we've released 5.0 with many improvements so maybe you can try to reproduce with that version?

**Comment by diogogallo** [comment]
Thanks for the reply Guy, we have updated to 5.0 and executing some tests to see if it was fixed

**Comment by GuyPardon** [comment]
Great to hear, thanks!

**Comment by xiangweidong** [comment]
@GuyPardon Hi, I also encountered this problem.After debugging, it was found that the problem appeared in ConnectionPoolWithConcurrentValidation.retrieveFirstAvailableConnection().Because the synchronous method claimFirstAvailablePooledConnection() is called here, the lock will be released, but at this time the maintenanceTimer thread may be executing removeConnectionsThatExceededMaxLifetime(), and the connection property in xpc is set to null; the following is my simplified code:`package com.atomikos.datasource.pool;

public class ConnectionPoolWithConcurrentValidation extends ConnectionPool
{
	protected Reapable retrieveFirstAvailableConnection() {
		Reapable ret = null;
		XPooledConnection xpc = claimFirstAvailablePooledConnection();
		if (xpc != null) {
			ret = concurrentlyTryToUse(xpc);
		}
		return ret;
	}

	private synchronized XPooledConnection claimFirstAvailablePooledConnection() {
		XPooledConnection ret = null;
		Iterator<XPooledConnection> it = connections.iterator();			
		while ( it.hasNext() && ret == null ) {
			XPooledConnection xpc =  it.next();
			if (xpc.markAsBeingAcquiredIfAvailable()) {
				ret = xpc;
			}
		}
		return ret;
	}

	private void init() throws ConnectionPoolException
	{
		if ( LOGGER.isTraceEnabled() ) LOGGER.logTrace ( this + ": initializing..." );
		addConnectionsIfMinPoolSizeNotReached();
		launchMaintenanceTimer();
	}

	private void launchMaintenanceTimer() {
		int maintenanceInterval = properties.getMaintenanceInterval();
		if ( maintenanceInterval <= 0 ) {
			if ( LOGGER.isTraceEnabled() ) LOGGER.logTrace ( this + ": using default maintenance interval..." );
			maintenanceInterval = DEFAULT_MAINTENANCE_INTERVAL;
		}
		maintenanceTimer = new PooledAlarmTimer ( maintenanceInterval * 1000 );
		maintenanceTimer.addAlarmTimerListener(new AlarmTimerListener() {
			public void alarm(AlarmTimer timer) {
				reapPool();
				removeConnectionsThatExceededMaxLifetime();
				addConnectionsIfMinPoolSizeNotReached();
				removeIdleConnectionsIfMinPoolSizeExceeded();
			}
		});
		TaskManager.SINGLETON.executeTask ( maintenanceTimer );
	}

	private synchronized void removeConnectionsThatExceededMaxLifetime()
	{
		long maxLifetime = properties.getMaxLifetime();
		if ( connections == null || maxLifetime <= 0 ) return;

		if ( LOGGER.isTraceEnabled() ) LOGGER.logTrace ( this + ": closing connections that exceeded maxLifetime" );

		Iterator<XPooledConnection> it = connections.iterator();
		while ( it.hasNext() ) {
			XPooledConnection xpc = it.next();
			long creationTime = xpc.getCreationTime();
			long now = System.currentTimeMillis();
			if ( xpc.isAvailable() &&  ( (now - creationTime) >= (maxLifetime * 1000L) ) ) {
				if ( LOGGER.isTraceEnabled() ) LOGGER.logTrace ( this + ": connection in use for more than " + maxLifetime + "s, destroying it: " + xpc );
				destroyPooledConnection(xpc);
				it.remove();
			}
		}
		logCurrentPoolSize();
	}
}
`

**Comment by timandy** [comment]
Fix `ConnectionPoolWithConcurrentValidation` without change the source code.


```java 
@Slf4j
public final class ConnectionPoolWithConcurrentValidationFixed extends ConnectionPoolWithConcurrentValidation {
    private static final Method removeConnectionsThatExceededMaxLifetimeMethod = ReflectionUtils.getMethod(ConnectionPool.class, "removeConnectionsThatExceededMaxLifetime", null, false);
    private static final Method addConnectionsIfMinPoolSizeNotReachedMethod = ReflectionUtils.getMethod(ConnectionPool.class, "addConnectionsIfMinPoolSizeNotReached", null, false);
    private static final Method removeIdleConnectionsIfMinPoolSizeExceededMethod = ReflectionUtils.getMethod(ConnectionPool.class, "removeIdleConnectionsIfMinPoolSizeExceeded", null, false);
    private static final Field maintenanceTimerField = ReflectionUtils.getField(ConnectionPool.class, "maintenanceTimer", false);
    private static final Field listenersField = ReflectionUtils.getField(PooledAlarmTimer.class, "listeners", false);
    private final ReadWriteLock lock = new ReentrantReadWriteLock(true);//公平读写锁

    /**
     * 构造函数
     */
    public ConnectionPoolWithConcurrentValidationFixed(ConnectionFactory connectionFactory, ConnectionPoolProperties properties) throws ConnectionPoolException {
        super(connectionFactory, properties);
        this.init();
    }

    /**
     * 调用完父构造函数后, 会先执行父类的初始化函数
     * 再执行本方法
     *
     * @see ConnectionPool#init()
     */
    @SuppressWarnings("JavadocReference")
    private void init() {
        this.fixMaintenanceTimer();
    }

    /**
     * 清理定时器里的监听方法, 使用新逻辑
     *
     * @see ConnectionPool#launchMaintenanceTimer()
     */
    @SuppressWarnings({"JavadocReference", "unchecked", "SynchronizationOnLocalVariableOrMethodParameter"})
    @SneakyThrows
    private void fixMaintenanceTimer() {
        PooledAlarmTimer maintenanceTimer = (PooledAlarmTimer) maintenanceTimerField.get(this);
        List<AlarmTimerListener> listeners = (List<AlarmTimerListener>) listenersField.get(maintenanceTimer);
        //清空监听
        synchronized (listeners) {
            listeners.clear();
        }
        //重新添加监听
        maintenanceTimer.addAlarmTimerListener(timer -> {
            this.reapPool();
            this.removeConnectionsThatExceededMaxLifetime();
            this.addConnectionsIfMinPoolSizeNotReached();
            this.removeIdleConnectionsIfMinPoolSizeExceeded();
        });
    }

    /**
     * 加写锁, 维护线程; 清理长时间使用的连接
     *
     * @see ConnectionPool#reapPool()
     */
    @Override
    public synchronized void reapPool() {
        this.lock.writeLock().lock();
        try {
            super.reapPool();
        } finally {
            this.lock.writeLock().unlock();
        }
    }

    /**
     * 加写锁, 维护线程; 清理声明周期大于指定值的连接
     *
     * @see ConnectionPool#removeConnectionsThatExceededMaxLifetime()
     */
    @SuppressWarnings("JavadocReference")
    @SneakyThrows
    private synchronized void removeConnectionsThatExceededMaxLifetime() {
        this.lock.writeLock().lock();
        try {
            removeConnectionsThatExceededMaxLifetimeMethod.invoke(this);
        } finally {
            this.lock.writeLock().unlock();
        }
    }

    /**
     * 加写锁, 维护线程; 如果总链接数不足最小连接数, 往池中添加新链接
     *
     * @see ConnectionPool#addConnectionsIfMinPoolSizeNotReached()
     */
    @SuppressWarnings("JavadocReference")
    @SneakyThrows
    private synchronized void addConnectionsIfMinPoolSizeNotReached() {
        this.lock.writeLock().lock();
        try {
            addConnectionsIfMinPoolSizeNotReachedMethod.invoke(this);
        } finally {
            this.lock.writeLock().unlock();
        }
    }

    /**
     * 加写锁, 维护线程; 如果总连接数超过了最小连接数, 并且连接空闲时间过长则清理
     *
     * @see ConnectionPool#removeIdleConnectionsIfMinPoolSizeExceeded()
     */
    @SuppressWarnings("JavadocReference")
    @SneakyThrows
    private synchronized void removeIdleConnectionsIfMinPoolSizeExceeded() {
        this.lock.writeLock().lock();
        try {
            removeIdleConnectionsIfMinPoolSizeExceededMethod.invoke(this);
        } finally {
            this.lock.writeLock().unlock();
        }
    }

    /**
     * 加读锁; 尝试回收连接时, 防止连接被维护线程释放
     *
     * @see ConnectionPool#launchMaintenanceTimer()
     */
    @SuppressWarnings("JavadocReference")
    @Override
    protected Reapable recycleConnectionIfPossible() throws Exception {
        this.lock.readLock().lock();
        try {
            return super.recycleConnectionIfPossible();
        } finally {
            this.lock.readLock().unlock();
        }
    }

    /**
     * 加读锁; 尝试获取连接时, 连接被维护线程释放
     *
     * @see ConnectionPool#launchMaintenanceTimer()
     */
    @SuppressWarnings("JavadocReference")
    @Override
    protected Reapable retrieveFirstAvailableConnection() {
        this.lock.readLock().lock();
        try {
            return super.retrieveFirstAvailableConnection();
        } finally {
            this.lock.readLock().unlock();
        }
    }
}

```

**Comment by xiangweidong** [comment]
董祥伟：18458874565  已收到您的发来的邮件，谢谢！
