### ISSUE TITLE
raised -4: the supplied XID is invalid for this XA resource with Tomcat 7.0.70

### ISSUE THREAD

**Issue by ftamios** [atomikos/transactions-essentials#39]
I just upgraded Atomikos and the following exception has been more frequent although random with Tomcat 7.0.70.

Caused by: com.atomikos.datasource.ResourceException: XA resource 'XXX_XADS': resume for XID '35312E31392E3135382E3230302E746D313532313632333330323234363030303138:35312E31392E3135382E3230302E746D3230' raised -4: the supplied XID is invalid for this XA resource

I identified some threads are not initializing the context properly as 'lookup("java:comp/UserTransaction")' has failed.
This is context.xml as recommended:
<Context sessionCookieName="JSESSIONID_XXX" swallowOutput="true" useHttpOnly="true" >
        <WatchedResource>WEB-INF/web.xml</WatchedResource>
	
	<Transaction factory="com.atomikos.icatch.jta.UserTransactionFactory"/>

Is there any known issue or any direction to fix it?

**Comment by GuyPardon** [comment]
When you say upgrade, from what version to what other version do you mean?

**Comment by ftamios** [comment]
The upgrade was from 3.9.3 to 4.0.6. I had seen the issue before, but now it's more frequent.

**Comment by GuyPardon** [comment]
It's not a known issue AFAIK...

**Comment by ftamios** [comment]
Most of the errors are related to the following OracleXAException. Along with Atomikos, JDBC driver was also upgraded to 12.1.0.1.0 (ojdbc7.jar).
Caused by: oracle.jdbc.xa.OracleXAException at oracle.jdbc.xa.OracleXAResource.checkError(OracleXAResource.java:1188) at oracle.jdbc.xa.client.OracleXAResource.start(OracleXAResource.java:253) at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:297)

In one of the scenarios, I saw 2 datasources involved pointing to the same database. The first one worked, but the second failed preparing statement. 

Do you suggest anything?

**Comment by GuyPardon** [comment]
I would recommend the following so we can have a look at your configuration:

https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

Thanks
