### ISSUE TITLE
Integration of Spring 5+ Hibernate 5 + Atomikos 4 + Tomcat Unable to locate current JTA transaction

### ISSUE THREAD

**Issue by sylar03** [atomikos/transactions-essentials#49]
Hello,
I have tried many different solutions, but getting the exception:

`org.hibernate.HibernateException: Unable to locate current JTA transaction at org.hibernate.context.internal.JTASessionContext.currentSession(JTASessionContext.java:75) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final] at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:465) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]`

I am using Atomikos 4.0.4, Hibernate 5.2.12, Spring 5.0.2 and Tomcat 8.
How to configure Spring 5 + Hibernate 5
This is my configuration
application-context.xml

```
<bean id="sessionFactory"
      class="org.springframework.orm.hibernate5.LocalSessionFactoryBean">
    <property name="configLocation">
        <value>classpath:hibernate.cfg.xml</value>
    </property>
    <property name="hibernateProperties">
        <props>
            <prop key="hibernate.cache.use_query_cache">true</prop>
            <prop key="hibernate.cache.use_second_level_cache">true</prop>
            <prop key="hibernate.cache.region.factory_class">org.hibernate.cache.ehcache.EhCacheRegionFactory</prop>
            <prop key="net.sf.ehcache.configurationResourceName">/ehcache/ehcache.xml</prop>
            <prop key="hibernate.connection.datasource">java:/comp/env/jdbc/myoracle</prop>
            <prop key="hibernate.transaction.jta.platform">cgaweb.common.atomikos.SpringJtaPlatformAdapter</prop>
            <prop key="hibernate.max_fetch_depth">2</prop>
            <prop key="hibernate.connection.autocommit">false</prop>
            <prop key="hibernate.connection.release_mode">after_transaction</prop>
            <prop key="hibernate.current_session_context_class">jta</prop>
            <prop key="javax.persistence.transactionType">jta</prop>
            <prop key="hibernate.dialect">org.hibernate.dialect.Oracle10gDialect</prop>
            <prop key="hibernate.show_sql">true</prop>
            <prop key="hibernate.id.new_generator_mappings">true</prop>
            <prop key="hibernate.mapping.precedence">class, hbm</prop>
            <prop key="connection.driver_class">oracle.jdbc.OracleDriver</prop>
        </props>
    </property>
</bean>

<!-- jta transaction -->
<bean id="atomikosTransactionService" class="com.atomikos.icatch.config.UserTransactionServiceImp" init-method="init" destroy-method="shutdownWait" >
<constructor-arg>
    <props>
        <prop key="com.atomikos.icatch.log_base_name">UserTransactionServiceImplog</prop>
    </props>
</constructor-arg>
</bean>
<bean id="atomikosTransactionManager" class="com.atomikos.icatch.jta.UserTransactionManager" init-method="init" destroy-method="close" depends-on="atomikosTransactionService">
    <property name="forceShutdown" value="true"/>
    <property name="transactionTimeout" value="300" />
</bean>
<bean id="atomikosUserTransaction" class="com.atomikos.icatch.jta.UserTransactionImp" depends-on="atomikosTransactionService">
    <property name="TransactionTimeout" value="300"/>
</bean>
<bean id="transactionManager" class="org.springframework.transaction.jta.JtaTransactionManager">
    <property name="transactionManager" ref="atomikosTransactionManager"></property>
    <property name="userTransaction" ref="atomikosUserTransaction"></property>
    <property name="allowCustomIsolationLevels" value="true"></property>
</bean>
<!-- Manager lookup-->
<bean id="springJtaPlatformAdapter" class="cgaweb.common.atomikos.SpringJtaPlatformAdapter">
    <property name="jtaTransactionManager" ref="transactionManager" />
</bean>

<!-- post construct -->
<bean class="org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor" />
<bean class="org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor" />

```

code of adapter 

```
public class SpringJtaPlatformAdapter extends AbstractJtaPlatform {
private static TransactionManager sTransactionManager;
private static UserTransaction sUserTransaction;
@Override
protected TransactionManager locateTransactionManager() {
    return sTransactionManager;
}
@Override
protected UserTransaction locateUserTransaction() {
    return sUserTransaction;
}
public void setJtaTransactionManager(JtaTransactionManager jtaTransactionManager) {
    sTransactionManager = jtaTransactionManager.getTransactionManager();
    sUserTransaction = jtaTransactionManager.getUserTransaction();
}
public void setTransactionManager(TransactionManager transactionManager) {
    sTransactionManager = transactionManager;
}
public void setUserTransaction(UserTransaction userTransaction) {
    sUserTransaction = userTransaction;
}


```
I have added  the following libs in my tomcat server  :

transaction-jta-4.0.4.jar
transaction-jdbc.4.0.4.jar
transaction-hibernate4-4.0.jar
transaction-api-4.0.4.jar
transactions-4.0.4.jar
jta-1.1.jar

EDIT 1 : it's seems that the current thread from spring is not associated to the thread tomcat in class CompositeTransactionManagerImp !
can you please help me to solve this issue ? Thanks

**Comment by GuyPardon** [comment]
It looks like you have class loading issues. If you're interested: we offer built-in Tomcat integration and free evaluation support as part of our free trial: https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

**Comment by GuyPardon** [comment]
Is this issue still current? Closing for now, please reopen if you disagree?
