### ISSUE TITLE
Deadlock on connection close

### ISSUE THREAD

**Issue by mafrankowski** [atomikos/transactions-essentials#50]
When one thread is getting jms connection from pool, while another one is doing jms connection cleanup deadlock occurs in atomikos code. Here is thread dump for version 3.9.3, but the same problem occurs in version 4.0.6.

"DefaultJmsListenerContainer3" - Thread t@153
   java.lang.Thread.State: BLOCKED
        at com.atomikos.jms.AtomikosPooledJmsConnection.onTerminated(AtomikosPooledJmsConnection.java:125)
        - waiting to lock <178e85e> (a com.atomikos.jms.AtomikosPooledJmsConnection) owned by "http-nio-9080-exec-6" t@85
        at com.atomikos.datasource.xa.session.SessionHandleState.fireTerminatedEvent(SessionHandleState.java:272)
        at com.atomikos.datasource.xa.session.SessionHandleState.notifySessionClosed(SessionHandleState.java:137)
        at com.atomikos.jms.AtomikosJmsXaSessionProxy.invoke(AtomikosJmsXaSessionProxy.java:137)
        - locked <130910b> (a com.atomikos.jms.AtomikosJmsXaSessionProxy)
        at com.sun.proxy.$Proxy138.close(Unknown Source)
        at com.atomikos.jms.AtomikosJmsConnectionProxy.close(AtomikosJmsConnectionProxy.java:268)
        - locked <15666ee> (a java.util.ArrayList)
        at com.atomikos.jms.AtomikosJmsConnectionProxy.invoke(AtomikosJmsConnectionProxy.java:150)
        at com.sun.proxy.$Proxy137.close(Unknown Source)

"http-nio-9080-exec-6" - Thread t@85
   java.lang.Thread.State: BLOCKED
        at com.atomikos.jms.AtomikosJmsConnectionProxy.isAvailable(AtomikosJmsConnectionProxy.java:335)
        - waiting to lock <15666ee> (a java.util.ArrayList) owned by "DefaultJmsListenerContainer3" t@153
        at com.atomikos.jms.AtomikosPooledJmsConnection.isAvailable(AtomikosPooledJmsConnection.java:95)
        - locked <178e85e> (a com.atomikos.jms.AtomikosPooledJmsConnection)
        at com.atomikos.datasource.pool.ConnectionPool.retrieveFirstAvailableConnection(ConnectionPool.java:207)
        at com.atomikos.datasource.pool.ConnectionPool.retrieveFirstAvailableConnectionAndGrowPoolIfNecessary(ConnectionPool.java:173)
        at com.atomikos.datasource.pool.ConnectionPool.findOrWaitForAnAvailableConnection(ConnectionPool.java:160)
        at com.atomikos.datasource.pool.ConnectionPool.borrowConnection(ConnectionPool.java:151)
        - locked <2dd1f4> (a com.atomikos.datasource.pool.ConnectionPool)
        at com.atomikos.jms.AtomikosConnectionFactoryBean.createConnection(AtomikosConnectionFactoryBean.java:616)

**Comment by GuyPardon** [comment]
We have fixed this in our commercial edition (ExtremeTransactions) but can consider a port to the community.

It was a reasonably large fix so I am reluctant about putting this out under 4.0.

For now we've scheduled this under TransactionsEssentials 5.0 then.

**Comment by GuyPardon** [comment]
Implemented in the 5.0 code base
