### ISSUE TITLE
XA resource 'XXXXX': resume for XID 

### ISSUE THREAD

**Issue by Josephrajsj** [atomikos/transactions-essentials#54]
Hi

I am getting below exception while starting the server

Caused by: com.atomikos.datasource.ResourceException: XA resource 'XXXXX': resume for XID '627769496E746572666163656465763132313533313833363830353032333030303031:627769496E74657266616365646576313231' raised -3: the XA resource detected an internal error
        at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:303)
        at com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40)
        at com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46)
        at com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:70)
        at com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:160)
        at com.atomikos.jdbc.AtomikosConnectionProxy.enlist(AtomikosConnectionProxy.java:207)
        at com.atomikos.jdbc.AtomikosConnectionProxy.invoke(AtomikosConnectionProxy.java:122)
        at com.sun.proxy.$Proxy303.prepareStatement(Unknown Source)
        at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:534)
        at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:452)
        at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1700)
        at org.hibernate.loader.Loader.doQuery(Loader.java:801)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
        at org.hibernate.loader.Loader.loadEntity(Loader.java:2037)
        at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:86)
        at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:76)
        at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3293)
        at org.hibernate.event.def.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:496)
        at org.hibernate.event.def.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:477)
        at org.hibernate.event.def.DefaultLoadEventListener.load(DefaultLoadEventListener.java:227)
        at org.hibernate.event.def.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:285)
        at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:152)
        at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:1090)
        at org.hibernate.impl.SessionImpl.get(SessionImpl.java:1005)
        at org.hibernate.impl.SessionImpl.get(SessionImpl.java:998)
        at com.bnymellon.bwi3.sdk.database.hibernate.HibernateDAO.get(HibernateDAO.java:109)
        ... 82 more
Caused by: oracle.jdbc.xa.OracleXAException
        at oracle.jdbc.xa.OracleXAResource.checkError(OracleXAResource.java:1101)
        at oracle.jdbc.xa.client.OracleXAResource.start(OracleXAResource.java:237)
        at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:297)
        ... 108 more    

when I use following db connect string in my data source

"jdbc:Oracle:thin:@(DESCRIPTION =(load_balance=off)(failover=on)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= host1 )(PORT=port1))(ADDRESS=(PROTOCOL=TCP)(HOST=host2)(PORT=port2)))(CONNECT_DATA=(SERVICE_NAME=Ser_Name)))   

whereas host1 is down and host2 is up.

Please help me to resolve.

**Comment by GuyPardon** [comment]
Sorry for the late reply. Is this still current?

**Comment by aakash0809** [comment]
Hi  Everyone,

We are using java 8,  spring  boot application 2.0.0.RELEASE ,  <artifactId>spring-web</artifactId>
      <version>5.0.4.RELEASE</version>  ,  Oracle database 11g version , Atomikios 4.0.6 version. 
 
While accessing the application  we are getting the below error , Please help.

2019-03-11 05:14:35.257  WARN 22552 --- [cTaskExecutor-3] c.a.jdbc.JdbcConnectionProxyHelper       : Error enlisting in transaction - connection might be broken? Please check the logs for more information...

com.atomikos.datasource.ResourceException: XA resource 'catcDataSource': resume for XID '31302E312E382E39352E746D313535323239323037353232363033303430:31302E312E382E39352E746D33303433' raised -7: the XA resource has become unavailable
        at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:303) ~[transactions-jta-4.0.6.jar!/:na]
        at com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40) ~[transactions-jta-4.0.6.jar!/:na]
        at com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46) ~[transactions-jta-4.0.6.jar!/:na]
        at com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:70) ~[transactions-jta-4.0.6.jar!/:na]
        at com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:160) ~[transactions-jta-4.0.6.jar!/:na]
        at com.atomikos.jdbc.AtomikosConnectionProxy.enlist(AtomikosConnectionProxy.java:207) ~[transactions-jdbc-4.0.6.jar!/:na]
        at com.atomikos.jdbc.AtomikosConnectionProxy.invoke(AtomikosConnectionProxy.java:122) ~[transactions-jdbc-4.0.6.jar!/:na]
        at com.sun.proxy.$Proxy115.prepareStatement(Unknown Source) [na:na]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.prepareQueryStatement(AbstractLoadPlanBasedLoader.java:226) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:190) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:121) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:86) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:167) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4087) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:508) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:478) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:219) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:278) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:121) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:89) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1239) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.internal.SessionImpl.access$1900(SessionImpl.java:203) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2803) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2777) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3406) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3375) [hibernate-core-5.2.14.Final.jar!/:5.2.14.Final]
        at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:350) [spring-orm-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at com.sun.proxy.$Proxy161.find(Unknown Source) [na:na]
        at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:304) [spring-orm-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at com.sun.proxy.$Proxy161.find(Unknown Source) [na:na]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findById(SimpleJpaRepository.java:235) [spring-data-jpa-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:377) [spring-data-commons-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200) [spring-data-commons-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:629) [spring-data-commons-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:593) [spring-data-commons-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578) [spring-data-commons-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) [spring-data-commons-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$660/350703813.proceedWithInvocation(Unknown Source) [spring-tx-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) [spring-tx-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) [spring-tx-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) [spring-tx-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135) [spring-data-jpa-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) [spring-data-commons-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at com.sun.proxy.$Proxy169.findById(Unknown Source) [na:na]
        at com.falabella.pim.dataprocessor.service.ItemProcessorService.processDividedData(ItemProcessorService.java:190) [pim-data-processor-1.0-SNAPSHOT.jar!/:na]
        at com.falabella.pim.dataprocessor.service.ItemProcessorService$$FastClassBySpringCGLIB$$744120bc.invoke(<generated>) [pim-data-processor-1.0-SNAPSHOT.jar!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at com.falabella.pim.dataprocessor.service.ItemProcessorService$$EnhancerBySpringCGLIB$$a14bdfe.processDividedData(<generated>) [pim-data-processor-1.0-SNAPSHOT.jar!/:na]
        at com.falabella.pim.dataprocessor.batch.dataprocessor.DataProcessItemProcessor.process(DataProcessItemProcessor.java:35) [pim-data-processor-1.0-SNAPSHOT.jar!/:na]
        at com.falabella.pim.dataprocessor.batch.dataprocessor.DataProcessItemProcessor.process(DataProcessItemProcessor.java:19) [pim-data-processor-1.0-SNAPSHOT.jar!/:na]
        at com.falabella.pim.dataprocessor.batch.dataprocessor.DataProcessItemProcessor$$FastClassBySpringCGLIB$$339c9c1.invoke(<generated>) [pim-data-processor-1.0-SNAPSHOT.jar!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) [spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at com.falabella.pim.dataprocessor.batch.dataprocessor.DataProcessItemProcessor$$EnhancerBySpringCGLIB$$cc27fe3.process(<generated>) [pim-data-processor-1.0-SNAPSHOT.jar!/:na]
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.doProcess(SimpleChunkProcessor.java:126) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor$1.doWithRetry(FaultTolerantChunkProcessor.java:227) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) [spring-retry-1.2.2.RELEASE.jar!/:na]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211) [spring-retry-1.2.2.RELEASE.jar!/:na]
        at org.springframework.batch.core.step.item.BatchRetryTemplate.execute(BatchRetryTemplate.java:217) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor.transform(FaultTolerantChunkProcessor.java:292) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:202) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) [spring-tx-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) [spring-batch-infrastructure-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) [spring-batch-infrastructure-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) [spring-batch-infrastructure-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136) [spring-batch-core-4.0.0.RELEASE.jar!/:4.0.0.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
Caused by: oracle.jdbc.xa.OracleXAException: null
        at oracle.jdbc.xa.OracleXAResource.checkError(OracleXAResource.java:1188) ~[ojdbc7.jar!/:12.1.0.1.0]
        at oracle.jdbc.xa.client.OracleXAResource.start(OracleXAResource.java:253) ~[ojdbc7.jar!/:12.1.0.1.0]
        at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:297) ~[transactions-jta-4.0.6.jar!/:na]
        ... 104 common frames omitted

-Aakash

**Comment by disheno** [comment]
> Sorry for the late reply. Is this still current?

did it solved?

**Comment by GuyPardon** [comment]
Looks like a network issue, not a bug.
