### ISSUE TITLE
Cannot commit transaction and no exception is thrown

### ISSUE THREAD

**Issue by jcarnus** [atomikos/transactions-essentials#70]
Hi,
We are using Atomikos 4.0.4 integrated with Spring. We randomly get the following error when the transaction try to commit

`-XA resource 'XAPPCDataSource': commit for XID '31302E3230312E3230372E3132352E746D313534343133303938373134333036383635:31302E3230312E3230372E3132352E746D36383639' raised -4: the supplied XID is invalid for this XA resource
 javax.transaction.xa.XAException: The function COMMIT: failed. The status is: -4. Error: "*** SQLJDBC_XA DTC_ERROR Context: xa_commit, state=1, StatusCode:-4 (0xFFFFFFFC) ***"
	at com.microsoft.sqlserver.jdbc.SQLServerXAResource.DTC_XA_Interface(SQLServerXAResource.java:645)
	at com.microsoft.sqlserver.jdbc.SQLServerXAResource.commit(SQLServerXAResource.java:808)
	at com.atomikos.datasource.xa.XAResourceTransaction.commit(XAResourceTransaction.java:555)
	at com.atomikos.icatch.imp.CommitMessage.send(CommitMessage.java:52)
	at com.atomikos.icatch.imp.CommitMessage.send(CommitMessage.java:23)
	at com.atomikos.icatch.imp.PropagationMessage.submit(PropagationMessage.java:67)
	at com.atomikos.icatch.imp.Propagator$PropagatorThread.run(Propagator.java:63)
	at com.atomikos.icatch.imp.Propagator.submitPropagationMessage(Propagator.java:42)
	at com.atomikos.icatch.imp.CoordinatorStateHandler.commitFromWithinCallback(CoordinatorStateHandler.java:373)
	at com.atomikos.icatch.imp.IndoubtStateHandler$1.doCommit(IndoubtStateHandler.java:112)
	at com.atomikos.icatch.imp.CoordinatorStateHandler.commitWithAfterCompletionNotification(CoordinatorStateHandler.java:581)
	at com.atomikos.icatch.imp.IndoubtStateHandler.commit(IndoubtStateHandler.java:107)
	at com.atomikos.icatch.imp.CoordinatorImp.commit(CoordinatorImp.java:548)
	at com.atomikos.icatch.imp.CoordinatorImp.terminate(CoordinatorImp.java:690)
	at com.atomikos.icatch.imp.CompositeTransactionImp.commit(CompositeTransactionImp.java:282)
	at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:172)
	at com.atomikos.icatch.jta.TransactionManagerImp.commit(TransactionManagerImp.java:414)
	at com.atomikos.icatch.jta.UserTransactionImp.commit(UserTransactionImp.java:86)
	at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1023)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:487)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)`

In reality, we had two error like this because we are using 2 databases at the same time. I don't explain why we got such issue randomly (and this is not the purpose of this ticket) but the main issue is that no Exception has been thrown to Spring. Due to this, From the Spring perpective, this commit had been done and I an not getting an error.
The code contains a link to bug 21552 but I am not able to find a bug tracker
Could you explain such a behavior ?
Thanks

**Comment by GuyPardon** [comment]
Hi,

Thanks for the feedback - I think this is a bug we fixed already. Please try either with the 4.0.6 release on maven central or with the commercial release where we give support (you can get a free trial at https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial). 

Cheers
Guy

**Comment by jcarnus** [comment]
Could you just indicate me where this has been fixed ? In 4.0.5 or 4.0.6 ?
Thanks

**Comment by GuyPardon** [comment]
4.0.6 is better in every way than 4.0.5

**Comment by jcarnus** [comment]
For sure, I just wanted to see in which release note entry this has been indicated ? From https://www.atomikos.com/Main/ReleaseNotes
