### ISSUE TITLE
XA Recover command execute failed due to communications link failure

### ISSUE THREAD

**Issue by cherrylzhao** [atomikos/transactions-essentials#72]
Hi, guys

I have used atomikos to provide XA transaction between different datasource in one user request.
everything looks good until backend recovery thread throw a communications link failure like this.

> [WARN ] 08:16:49.254 [Atomikos:1] c.a.r.xa.XaResourceRecoveryManager - Error while retrieving xids from resource - will retry later...
com.mysql.jdbc.jdbc2.optional.MysqlXAException: Undetermined error occurred in the underlying Connection - check your data for consistency
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:586)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.recover(MysqlXAConnection.java:316)
	at com.mysql.jdbc.jdbc2.optional.SuspendableXAConnection.recover(SuspendableXAConnection.java:155)
	at com.atomikos.datasource.xa.RecoveryScan.recoverXids(RecoveryScan.java:32)
	at com.atomikos.recovery.xa.XaResourceRecoveryManager.retrievePreparedXidsFromXaResource(XaResourceRecoveryManager.java:158)
	at com.atomikos.recovery.xa.XaResourceRecoveryManager.recover(XaResourceRecoveryManager.java:67)
	at com.atomikos.datasource.xa.XATransactionalResource.recover(XATransactionalResource.java:451)
	at com.atomikos.icatch.imp.TransactionServiceImp.performRecovery(TransactionServiceImp.java:490)
	at com.atomikos.icatch.imp.TransactionServiceImp.access$000(TransactionServiceImp.java:56)
	at com.atomikos.icatch.imp.TransactionServiceImp$1.alarm(TransactionServiceImp.java:471)
	at com.atomikos.timing.PooledAlarmTimer.notifyListeners(PooledAlarmTimer.java:95)
	at com.atomikos.timing.PooledAlarmTimer.run(PooledAlarmTimer.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.recover(MysqlXAConnection.java:295)
	... 13 common frames omitted
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
	... 21 common frames omitted

I have debug the code and found recovery thread will iterate the registered `JdbcTransactionalResource ` and send `xaResource.recover(XAResource.TMSTARTRSCAN)` command  to retrieve xids. it seems that `XAResource.TMNOFLAGS` will not be send if `xidsFromLastScan` is empty. when recovery thread execute next time, error will happen.
I will be appreciate if you give me some hint.

thanks!

### Basic info
Atomikos version: 4.0.4, 4.0.6
database: mysql 5.7.24
JDBC-driver:  5.1.42
XADataSource: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
usage way: AtomikosDataSourceBean
### XADataSource configuration
`
  private Properties getMySQLXAProperties(final DataSourceParameter dataSourceParameter) {
        Properties result = new Properties();
        result.setProperty("user", dataSourceParameter.getUsername());
        result.setProperty("password", Optional.fromNullable(dataSourceParameter.getPassword()).or(""));
        result.setProperty("URL", dataSourceParameter.getUrl());
        result.setProperty("pinGlobalTxToPhysicalConnection", Boolean.TRUE.toString());
        result.setProperty("autoReconnect", Boolean.TRUE.toString());
        result.setProperty("useServerPrepStmts", Boolean.TRUE.toString());
        result.setProperty("cachePrepStmts", Boolean.TRUE.toString());
        result.setProperty("prepStmtCacheSize", "250");
        result.setProperty("prepStmtCacheSqlLimit", "2048");
        result.setProperty("useLocalSessionState", Boolean.TRUE.toString());
        result.setProperty("rewriteBatchedStatements", Boolean.TRUE.toString());
        result.setProperty("cacheResultSetMetadata", Boolean.TRUE.toString());
        result.setProperty("cacheServerConfiguration", Boolean.TRUE.toString());
        result.setProperty("elideSetAutoCommits", Boolean.TRUE.toString());
        result.setProperty("maintainTimeStats", Boolean.FALSE.toString());
        result.setProperty("netTimeoutForStreamingResults", "0");
        return result;
    }
`

### customize configuration:
com.atomikos.icatch.serial_jta_transactions = false
com.atomikos.icatch.default_jta_timeout = 1000000
com.atomikos.icatch.max_actives = 10000
com.atomikos.icatch.recovery_delay= 30000

**Comment by GuyPardon** [comment]
Thanks for sharing!

**Comment by jpnffigueiredo** [comment]
> I have found the reason. our mysql have modified interactive_timeout, wait_timeout. `interactive_timeout = 30 wait_timeout = 30` while doing XA recover, physical connection have expired, then error happened.

This is an old issue, but I'm facing the same problem with a similar exception. These mysql timeouts values were also modified and `com.atomikos.icatch.recovery_delay` was adjusted to a lower value than `wait_timeout`.

```
[Atomikos:1] WARN  com.atomikos.datasource.xa.XATransactionalResource- Undetermined error occurred in the underlying Connection - check your data for consistency
com.mysql.cj.jdbc.MysqlXAException: Undetermined error occurred in the underlying Connection - check your data for consistency
    at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:347) ~[mysql-connector-java-8.0.17.jar:8.0.17]
    at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:189) ~[mysql-connector-java-8.0.17.jar:8.0.17]
    at com.mysql.cj.jdbc.SuspendableXAConnection.recover(SuspendableXAConnection.java:143) ~[mysql-connector-java-8.0.17.jar:8.0.17]
    at com.atomikos.datasource.xa.RecoveryScan.recoverXids(RecoveryScan.java:32) ~[transactions-jta-6.0.0.jar:?]
    at com.atomikos.recovery.xa.XARecoveryManager.retrievePreparedXidsFromXaResource(XARecoveryManager.java:265) ~[transactions-jta-6.0.0.jar:?]
    at com.atomikos.recovery.xa.XARecoveryManager.recover(XARecoveryManager.java:93) ~[transactions-jta-6.0.0.jar:?]
    at com.atomikos.datasource.xa.XATransactionalResource.recover(XATransactionalResource.java:375) ~[transactions-jta-6.0.0.jar:?]
    at com.atomikos.icatch.imp.RecoveryDomainService.performRecovery(RecoveryDomainService.java:82) ~[transactions-6.0.0.jar:?]
    at com.atomikos.icatch.imp.RecoveryDomainService$1.alarm(RecoveryDomainService.java:57) ~[transactions-6.0.0.jar:?]
    at com.atomikos.timing.PooledAlarmTimer.notifyListeners(PooledAlarmTimer.java:101) ~[atomikos-util-6.0.0.jar:?]
    at com.atomikos.timing.PooledAlarmTimer.run(PooledAlarmTimer.java:88) ~[atomikos-util-6.0.0.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_345]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_345]
    at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 1,400,000 milliseconds ago.  The last packet sent successfully to the server was 1,400,004 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
    at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.17.jar:8.0.17]
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.17.jar:8.0.17]
    at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200) ~[mysql-connector-java-8.0.17.jar:8.0.17]
    at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:168) ~[mysql-connector-java-8.0.17.jar:8.0.17]
```

We have:
```
wait_timeout=1800000
com.atomikos.icatch.recovery_delay=1400000
```

It seams that the connection used in `JdbcTransactionalResource` was closed by mysql. This connection is created in `refreshXAConnection` from `JdbcTransactionalResource`.

I can not see where this connection is refreshed, because `needsRefresh` from `XATransactionalResource` is comparing with `isSameRM` method.

Is possible that `xaConnection` from `JdbcTransactionalResource` is not refreshing until this exception in recover method?

**Comment by GuyPardon** [comment]
It depends on the implementation of isSameRM. I did not check, but maybe it's not doing network IO in the case of MySQL?

**Comment by jpnffigueiredo** [comment]
> It depends on the implementation of isSameRM. I did not check, but maybe it's not doing network IO in the case of MySQL?

It does not use network IO to check connection. We are using `MysqlXADataSource` that creates `SuspendableXAConnection` and is implemented like this:

```Java
@Override
public boolean isSameRM(XAResource xaRes) throws XAException {
    return xaRes == this;
}

```

But even MysqlXAConnection does not check network. The isSameRM method is also used in equals method of XATransactionalResource, so (maybe) will be very expensive to check like that?

It seams that XATransactionalResource is executing recover with a closed connection, and refresh does not check if connection is "valid".

We only have this problem when wait_timeout is different from default value. But while describing this here, i think it must be a configuration issue from our side, because if com.atomikos.icatch.recovery_delay is less than wait_timeout value from mysql, then recover is always executed with an active connection. Using this connection will reset de wait_timeout until next recover, so connection must be active.
