### ISSUE TITLE
The method 'xa_commit' has failed with errorCode '-6'

### ISSUE THREAD

**Issue by vg21** [atomikos/transactions-essentials#82]
While processing a message in WebSphere MQ following error occasionally happens. Also message is removed from the queue and not re-processed.

08:35:28.681 [Atomikos:128655] ERROR c.atomikos.icatch.imp.CommitMessage - Unexpected error in commit 
com.atomikos.icatch.SysException: XA resource 'WSXXX': commit for 
XID '...' raised -6: 
the XA resource did not expect this command in the current context 
at com.atomikos.datasource.xa.XAResourceTransaction.commit(XAResourceTransaction.java:596)
at com.atomikos.icatch.imp.CommitMessage.send(CommitMessage.java:52) 
at com.atomikos.icatch.imp.CommitMessage.send(CommitMessage.java:23) 
at com.atomikos.icatch.imp.PropagationMessage.submit(PropagationMessage.java:67) 
at com.atomikos.icatch.imp.Propagator$PropagatorThread.run(Propagator.java:63) 
at com.atomikos.icatch.imp.Propagator.submitPropagationMessage(Propagator.java:42) 
at com.atomikos.icatch.imp.HeurHazardStateHandler.onTimeout(HeurHazardStateHandler.java:71)
at com.atomikos.icatch.imp.CoordinatorImp.alarm(CoordinatorImp.java:650) 
at com.atomikos.timing.PooledAlarmTimer.notifyListeners(PooledAlarmTimer.java:95) 
at com.atomikos.timing.PooledAlarmTimer.run(PooledAlarmTimer.java:82) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: javax.transaction.xa.XAException: The method 'xa_commit' has failed with errorCode '-6'. 
at com.ibm.mq.jmqi.JmqiXAResource.commit(JmqiXAResource.java:407) 
at com.atomikos.datasource.xa.XAResourceTransaction.commit(XAResourceTransaction.java:557)
... 12 common frames omitted

Atomikos version: 4.0.72

**Comment by GuyPardon** [comment]
4.0.72 is a commercial release - please contact Atomikos support via your subscription guidelines.
