### ISSUE TITLE
IllegalStateException: State is no longer ACTIVE but ACTIVE during transaction rollback

### ISSUE THREAD

**Issue by Mobe91** [atomikos/transactions-essentials#89]
Today I got this exception during a transaction rollback. Does not look right somehow 😅 

```
[Atomikos:14] WARN  2019-04-11T20:17:36.809 c.a.icatch.imp.ActiveStateHandler:24 Transaction 10.0.0.6.tm155500662420800017 has timed out - rolling back... 
[Atomikos:14] WARN  2019-04-11T20:17:36.921 o.h.r.t.b.j.i.s.SynchronizationCallbackCoordinatorTrackingImpl:66 HHH000451: Transaction afterCompletion called by a background thread; delaying afterCompletion processing until the original thread can handle it. [status=4] 
[http-nio-8080-exec-10] ERROR 2019-04-11T20:17:36.934 o.s.t.i.TransactionInterceptor:554 Application exception overridden by rollback exception 
java.lang.IllegalStateException: 10.0.0.6.tm155500662420800017 is no longer active but in state TERMINATED
[http-nio-8080-exec-10] ERROR 2019-04-11T20:17:36.990 c.o.a.w.e.e.UnhandledExceptionHandler:36 Request failed: uri=****
org.springframework.transaction.TransactionSystemException: Unexpected internal transaction state; nested exception is java.lang.IllegalStateException: State is no longer ACTIVE but ACTIVE
Caused by: java.lang.IllegalStateException: State is no longer ACTIVE but ACTIVE
	at com.atomikos.icatch.imp.CompositeTransactionImp.localTestAndSetTransactionStateHandler(CompositeTransactionImp.java:101)
	at com.atomikos.icatch.imp.TransactionStateHandler.rollbackWithStateCheck(TransactionStateHandler.java:179)
	at com.atomikos.icatch.imp.CompositeTransactionImp.doRollback(CompositeTransactionImp.java:201)
	at com.atomikos.icatch.imp.CompositeTransactionImp.rollback(CompositeTransactionImp.java:314)
	at com.atomikos.icatch.jta.TransactionImp.rollback(TransactionImp.java:196)
	at com.atomikos.icatch.jta.TransactionManagerImp.rollback(TransactionManagerImp.java:436)
	at com.atomikos.icatch.jta.UserTransactionManager.rollback(UserTransactionManager.java:198)
	at org.springframework.transaction.jta.JtaTransactionManager.doRollback(JtaTransactionManager.java:1061)
	... 121 common frames omitted
```

Unfortunately, I do not know how this can be reproduced.

I am using transaction-essentials 5.0.0-SNAPSHOT / commit 2e5a875.

**Comment by GuyPardon** [comment]
Thanks, this looks like a race condition between the application thread and the transaction timeout thread. Try setting the startup property:

com.atomikos.icatch.threaded_2pc=false

Threaded 2pc is useful only in transactions across REST services, and supported in the commercial code only.
