### ISSUE TITLE
what happen with atomikos5.0.0 

### ISSUE THREAD

**Issue by jenopob** [atomikos/transactions-essentials#98]
should I change any property in jta.properties to solve this pro
INFO   | jvm 1    | 2019/11/06 20:43:30 | 2019-11-06 20:43:30.760 ERROR 21944 --- [    Atomikos:11] c.a.icatch.imp.RecoveryDomainService     : Log corrupted - restart JVM
INFO   | jvm 1    | 2019/11/06 20:43:30 | 
INFO   | jvm 1    | 2019/11/06 20:43:30 | com.atomikos.recovery.LogReadException: Log corrupted - restart JVM
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at com.atomikos.recovery.fs.CachedRepository.assertNotCorrupted(CachedRepository.java:137) ~[transactions-5.0.0.jar:na]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at com.atomikos.recovery.fs.CachedRepository.findAllCommittingCoordinatorLogEntries(CachedRepository.java:145) ~[transactions-5.0.0.jar:na]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at com.atomikos.recovery.fs.RecoveryLogImp.getExpiredPendingCommittingTransactionRecordsAt(RecoveryLogImp.java:109) ~[transactions-5.0.0.jar:na]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at com.atomikos.icatch.imp.RecoveryDomainService.performRecovery(RecoveryDomainService.java:80) ~[transactions-5.0.0.jar:na]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at com.atomikos.icatch.imp.RecoveryDomainService$1.alarm(RecoveryDomainService.java:61) [transactions-5.0.0.jar:na]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at com.atomikos.timing.PooledAlarmTimer.notifyListeners(PooledAlarmTimer.java:94) [atomikos-util-5.0.0.jar:na]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at com.atomikos.timing.PooledAlarmTimer.run(PooledAlarmTimer.java:81) [atomikos-util-5.0.0.jar:na]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
INFO   | jvm 1    | 2019/11/06 20:43:30 | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]

**Comment by GuyPardon** [comment]
Looks like a disk problem. Did you try with 5.0.3?

**Comment by jenopob** [comment]
haven't yet,I will have a try, then report again,Thanks!

**Comment by jenopob** [comment]
> Looks like a disk problem. Did you try with 5.0.3?

I try 5.0.3,the same error happen again as follows:is any config properties should be set in jta.properties? thanks for any help.

# Set output directory where console file and other files are to be put
# make sure this directory exists!
#
# com.atomikos.icatch.output_dir = ./

# Set directory of log files; make sure this directory exists!
#
# com.atomikos.icatch.log_base_dir = ./


INFO   | jvm 1    | 2019/11/12 22:16:01 | 2019-11-12 22:16:01.765 ERROR 31553 --- [    Atomikos:11] c.a.icatch.imp.RecoveryDomainService     : Log corrupted - restart JVM
INFO   | jvm 1    | 2019/11/12 22:16:01 | 
INFO   | jvm 1    | 2019/11/12 22:16:01 | com.atomikos.recovery.LogReadException: Log corrupted - restart JVM
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at com.atomikos.recovery.fs.CachedRepository.assertNotCorrupted(CachedRepository.java:137) ~[transactions-5.0.3.jar:na]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at com.atomikos.recovery.fs.CachedRepository.findAllCommittingCoordinatorLogEntries(CachedRepository.java:145) ~[transactions-5.0.3.jar:na]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at com.atomikos.recovery.fs.RecoveryLogImp.getExpiredPendingCommittingTransactionRecordsAt(RecoveryLogImp.java:52) ~[transactions-5.0.3.jar:na]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at com.atomikos.icatch.imp.RecoveryDomainService.performRecovery(RecoveryDomainService.java:76) ~[transactions-5.0.3.jar:na]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at com.atomikos.icatch.imp.RecoveryDomainService$1.alarm(RecoveryDomainService.java:55) [transactions-5.0.3.jar:na]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at com.atomikos.timing.PooledAlarmTimer.notifyListeners(PooledAlarmTimer.java:94) [atomikos-util-5.0.3.jar:na]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at com.atomikos.timing.PooledAlarmTimer.run(PooledAlarmTimer.java:81) [atomikos-util-5.0.3.jar:na]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
INFO   | jvm 1    | 2019/11/12 22:16:01 | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
INFO   | jvm 1    | 2019/11/12 22:16:01 |

**Comment by GuyPardon** [comment]
Does this happen repeatedly / predictably or only after a while?

**Comment by jenopob** [comment]
It happens per 10 mins

**Comment by GuyPardon** [comment]
OK thanks. We'll have to do some analysis then to find out. May I suggest a free trial of our commercial offering? If it happens with 4.0 and 5.0 then it must be something specific to your installation because we have never had this kind of report...

**Comment by jenopob** [comment]
before we use 5.0 ,we used version 4.0.6 as usual ,and it works well.how to join a free trial of commercial version.please show me the way, thanks a lot .
<img width="922" alt="Screen Shot 2019-11-13 at 00 00 19" src="https://user-images.githubusercontent.com/4093865/68688292-7512ce00-05a9-11ea-9f0d-bb5c84847334.png">

**Comment by GuyPardon** [comment]
Hi, the free trial is here:

https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

Thanks

**Comment by jenopob** [comment]
I catch the source code , RecoveryLogImp.isActive() method is always return true,
what 's the function of RecoveryLog. In my jta.properties com.atomikos.icatch.enable_logging=true
should turn false ?

**Comment by jenopob** [comment]
search from google, it solved when updated to version 4.0.6.
why it's happened in 5.0.3 version,:)

**Comment by GuyPardon** [comment]
The method isActive returns true by default but sometimes does otherwise in our commercial LogCloud.

If you disable logging then you don't have real transactions, probably not what you want.

If you are using 5.0.3 on top of the logs from 4.0 then this would explain the issue.

**Comment by GuyPardon** [comment]
Is there is prior log entry of level FATAL?

**Comment by jenopob** [comment]
I use com.atomikos.icatch.console_log_level=WARN,
the error log above appears every ten mins.

**Comment by GuyPardon** [comment]
Yes, but it can only be caused by something that is logged as FATAL earlier on. Do you see such an entry?

**Comment by jenopob** [comment]
no ,I haven't see the entry

**Comment by GuyPardon** [comment]
Strange - technically it is impossible for this condition to happen without a FATAL log entry before...
